//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.04 at 05:03:03 PM MESZ 
//


package de.decidr.model.workflowmodel.webservices;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.decidr.model.workflowmodel.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mapping_QNAME = new QName("http://decidr.de/schema/wsmapping", "mapping");
    private final static QName _Query_QNAME = new QName("http://docs.oasis-open.org/wsbpel/2.0/varprop", "query");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.decidr.model.workflowmodel.webservices
     * 
     */
    public ObjectFactory() {
        // XXX: document: why is this empty
    }

    /**
     * Create an instance of {@link WebserviceMapping }
     * 
     */
    public WebserviceMapping createWebserviceMapping() {
        return new WebserviceMapping();
    }

    /**
     * Create an instance of {@link TExtensibleElements }
     * 
     */
    public TExtensibleElements createTExtensibleElements() {
        return new TExtensibleElements();
    }

    /**
     * Create an instance of {@link PropertyAliases }
     * 
     */
    public PropertyAliases createPropertyAliases() {
        return new PropertyAliases();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link Documentation }
     * 
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link TQuery }
     * 
     */
    public TQuery createTQuery() {
        return new TQuery();
    }

    /**
     * Create an instance of {@link PropertyAlias }
     * 
     */
    public PropertyAlias createPropertyAlias() {
        return new PropertyAlias();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebserviceMapping }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://decidr.de/schema/wsmapping", name = "mapping")
    public JAXBElement<WebserviceMapping> createMapping(WebserviceMapping value) {
        return new JAXBElement<WebserviceMapping>(_Mapping_QNAME, WebserviceMapping.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TQuery }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wsbpel/2.0/varprop", name = "query")
    public JAXBElement<TQuery> createQuery(TQuery value) {
        return new JAXBElement<TQuery>(_Query_QNAME, TQuery.class, null, value);
    }

}
