package de.decidr.webservices.email;

import java.net.MalformedURLException;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.1.3 Fri Jun 12 16:46:57 CEST 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "malformedURLException", targetNamespace = "http://decidr.de/webservices/Email")
public class MalformedURLExceptionWrapper extends MalformedURLException {
    public static final long serialVersionUID = 20090612164657L;

    private java.lang.String malformedURLException;

    public MalformedURLExceptionWrapper() {
        super();
    }

    public MalformedURLExceptionWrapper(String message) {
        super(message);
    }

    public MalformedURLExceptionWrapper(String message,
            java.lang.String malformedURLException) {
        super(message);
        this.malformedURLException = malformedURLException;
    }

    public java.lang.String getFaultInfo() {
        return this.malformedURLException;
    }
}
