/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.07 at 09:21:14 PM MEZ 
//

package de.decidr.model.workflowmodel.bpel;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * 
 * XSD Authors: The child element correlations needs to be a Local Element
 * Declaration, because there is another correlations element defined for the
 * non-invoke activities.
 * 
 * 
 * <p>
 * Java class for tInvoke complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tInvoke">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tActivity">
 *       &lt;sequence>
 *         &lt;element name="correlations" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tCorrelationsWithPattern" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}catch" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}catchAll" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}compensationHandler" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}toParts" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}fromParts" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="partnerLink" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="portType" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="inputVariable" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}BPELVariableName" />
 *       &lt;attribute name="outputVariable" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}BPELVariableName" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInvoke", propOrder = { "correlations", "_catch", "catchAll",
        "compensationHandler", "toParts", "fromParts" })
public class Invoke extends Activity {

    protected CorrelationsWithPattern correlations;
    @XmlElement(name = "catch")
    protected List<Catch> _catch;
    protected ActivityContainer catchAll;
    protected ActivityContainer compensationHandler;
    protected ToParts toParts;
    protected FromParts fromParts;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String partnerLink;
    @XmlAttribute
    protected QName portType;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String operation;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inputVariable;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outputVariable;

    /**
     * Gets the value of the catch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the catch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Catch }
     * 
     * 
     */
    public List<Catch> getCatch() {
        if (_catch == null) {
            _catch = new ArrayList<Catch>();
        }
        return this._catch;
    }

    /**
     * Gets the value of the catchAll property.
     * 
     * @return possible object is {@link ActivityContainer }
     * 
     */
    public ActivityContainer getCatchAll() {
        return catchAll;
    }

    /**
     * Gets the value of the compensationHandler property.
     * 
     * @return possible object is {@link ActivityContainer }
     * 
     */
    public ActivityContainer getCompensationHandler() {
        return compensationHandler;
    }

    /**
     * Gets the value of the correlations property.
     * 
     * @return possible object is {@link CorrelationsWithPattern }
     * 
     */
    public CorrelationsWithPattern getCorrelations() {
        return correlations;
    }

    /**
     * Gets the value of the fromParts property.
     * 
     * @return possible object is {@link FromParts }
     * 
     */
    public FromParts getFromParts() {
        return fromParts;
    }

    /**
     * Gets the value of the inputVariable property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getInputVariable() {
        return inputVariable;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Gets the value of the outputVariable property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOutputVariable() {
        return outputVariable;
    }

    /**
     * Gets the value of the partnerLink property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPartnerLink() {
        return partnerLink;
    }

    /**
     * Gets the value of the portType property.
     * 
     * @return possible object is {@link QName }
     * 
     */
    public QName getPortType() {
        return portType;
    }

    /**
     * Gets the value of the toParts property.
     * 
     * @return possible object is {@link ToParts }
     * 
     */
    public ToParts getToParts() {
        return toParts;
    }

    public boolean isSetCatch() {
        return ((this._catch != null) && (!this._catch.isEmpty()));
    }

    public boolean isSetCatchAll() {
        return (this.catchAll != null);
    }

    public boolean isSetCompensationHandler() {
        return (this.compensationHandler != null);
    }

    public boolean isSetCorrelations() {
        return (this.correlations != null);
    }

    public boolean isSetFromParts() {
        return (this.fromParts != null);
    }

    public boolean isSetInputVariable() {
        return (this.inputVariable != null);
    }

    public boolean isSetOperation() {
        return (this.operation != null);
    }

    public boolean isSetOutputVariable() {
        return (this.outputVariable != null);
    }

    public boolean isSetPartnerLink() {
        return (this.partnerLink != null);
    }

    public boolean isSetPortType() {
        return (this.portType != null);
    }

    public boolean isSetToParts() {
        return (this.toParts != null);
    }

    /**
     * Sets the value of the catchAll property.
     * 
     * @param value
     *            allowed object is {@link ActivityContainer }
     * 
     */
    public void setCatchAll(ActivityContainer value) {
        this.catchAll = value;
    }

    /**
     * Sets the value of the compensationHandler property.
     * 
     * @param value
     *            allowed object is {@link ActivityContainer }
     * 
     */
    public void setCompensationHandler(ActivityContainer value) {
        this.compensationHandler = value;
    }

    /**
     * Sets the value of the correlations property.
     * 
     * @param value
     *            allowed object is {@link CorrelationsWithPattern }
     * 
     */
    public void setCorrelations(CorrelationsWithPattern value) {
        this.correlations = value;
    }

    /**
     * Sets the value of the fromParts property.
     * 
     * @param value
     *            allowed object is {@link FromParts }
     * 
     */
    public void setFromParts(FromParts value) {
        this.fromParts = value;
    }

    /**
     * Sets the value of the inputVariable property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setInputVariable(String value) {
        this.inputVariable = value;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Sets the value of the outputVariable property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOutputVariable(String value) {
        this.outputVariable = value;
    }

    /**
     * Sets the value of the partnerLink property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPartnerLink(String value) {
        this.partnerLink = value;
    }

    /**
     * Sets the value of the portType property.
     * 
     * @param value
     *            allowed object is {@link QName }
     * 
     */
    public void setPortType(QName value) {
        this.portType = value;
    }

    /**
     * Sets the value of the toParts property.
     * 
     * @param value
     *            allowed object is {@link ToParts }
     * 
     */
    public void setToParts(ToParts value) {
        this.toParts = value;
    }

    public void unsetCatch() {
        this._catch = null;
    }

}
