/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.07 at 09:21:14 PM MEZ 
//

package de.decidr.model.workflowmodel.bpel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * 
 * XSD Authors: The child element correlations needs to be a Local Element
 * Declaration, because there is another correlations element defined for the
 * invoke activity.
 * 
 * 
 * <p>
 * Java class for tReceive complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tReceive">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tActivity">
 *       &lt;sequence>
 *         &lt;element name="correlations" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tCorrelations" minOccurs="0"/>
 *         &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}fromParts" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="partnerLink" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="portType" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="operation" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="variable" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}BPELVariableName" />
 *       &lt;attribute name="createInstance" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tBoolean" default="no" />
 *       &lt;attribute name="messageExchange" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tReceive", propOrder = { "correlations", "fromParts" })
public class Receive extends Activity {

    protected Correlations correlations;
    protected FromParts fromParts;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String partnerLink;
    @XmlAttribute
    protected QName portType;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String operation;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String variable;
    @XmlAttribute
    protected Boolean createInstance;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String messageExchange;

    /**
     * Gets the value of the correlations property.
     * 
     * @return possible object is {@link Correlations }
     * 
     */
    public Correlations getCorrelations() {
        return correlations;
    }

    /**
     * Gets the value of the createInstance property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getCreateInstance() {
        if (createInstance == null) {
            return Boolean.NO;
        } else {
            return createInstance;
        }
    }

    /**
     * Gets the value of the fromParts property.
     * 
     * @return possible object is {@link FromParts }
     * 
     */
    public FromParts getFromParts() {
        return fromParts;
    }

    /**
     * Gets the value of the messageExchange property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMessageExchange() {
        return messageExchange;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Gets the value of the partnerLink property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPartnerLink() {
        return partnerLink;
    }

    /**
     * Gets the value of the portType property.
     * 
     * @return possible object is {@link QName }
     * 
     */
    public QName getPortType() {
        return portType;
    }

    /**
     * Gets the value of the variable property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVariable() {
        return variable;
    }

    public boolean isSetCorrelations() {
        return (this.correlations != null);
    }

    public boolean isSetCreateInstance() {
        return (this.createInstance != null);
    }

    public boolean isSetFromParts() {
        return (this.fromParts != null);
    }

    public boolean isSetMessageExchange() {
        return (this.messageExchange != null);
    }

    public boolean isSetOperation() {
        return (this.operation != null);
    }

    public boolean isSetPartnerLink() {
        return (this.partnerLink != null);
    }

    public boolean isSetPortType() {
        return (this.portType != null);
    }

    public boolean isSetVariable() {
        return (this.variable != null);
    }

    /**
     * Sets the value of the correlations property.
     * 
     * @param value
     *            allowed object is {@link Correlations }
     * 
     */
    public void setCorrelations(Correlations value) {
        this.correlations = value;
    }

    /**
     * Sets the value of the createInstance property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setCreateInstance(Boolean value) {
        this.createInstance = value;
    }

    /**
     * Sets the value of the fromParts property.
     * 
     * @param value
     *            allowed object is {@link FromParts }
     * 
     */
    public void setFromParts(FromParts value) {
        this.fromParts = value;
    }

    /**
     * Sets the value of the messageExchange property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMessageExchange(String value) {
        this.messageExchange = value;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Sets the value of the partnerLink property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPartnerLink(String value) {
        this.partnerLink = value;
    }

    /**
     * Sets the value of the portType property.
     * 
     * @param value
     *            allowed object is {@link QName }
     * 
     */
    public void setPortType(QName value) {
        this.portType = value;
    }

    /**
     * Sets the value of the variable property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVariable(String value) {
        this.variable = value;
    }

}
