//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.20 at 12:30:36 AM MESZ 
//


package de.decidr.model.workflowmodel.humantask;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.decidr.model.workflowmodel.humantask package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HumanTaskData_QNAME = new QName("http://decidr.de/schema/humanTask", "humanTaskData");
    private final static QName _Content_QNAME = new QName("http://decidr.de/schema/humanTask", "content");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.decidr.model.workflowmodel.humantask
     * 
     */
    public ObjectFactory() {
        // MA: document: why is this empty
    }

    /**
     * Create an instance of {@link TParameters }
     * 
     */
    public TParameters createTParameters() {
        return new TParameters();
    }

    /**
     * Create an instance of {@link TTaskItem }
     * 
     */
    public TTaskItem createTTaskItem() {
        return new TTaskItem();
    }

    /**
     * Create an instance of {@link TParameter }
     * 
     */
    public TParameter createTParameter() {
        return new TParameter();
    }

    /**
     * Create an instance of {@link TInformation }
     * 
     */
    public TInformation createTInformation() {
        return new TInformation();
    }

    /**
     * Create an instance of {@link THumanTaskData }
     * 
     */
    public THumanTaskData createTHumanTaskData() {
        return new THumanTaskData();
    }

    /**
     * Create an instance of {@link TContent }
     * 
     */
    public TContent createTContent() {
        return new TContent();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THumanTaskData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://decidr.de/schema/humanTask", name = "humanTaskData")
    public JAXBElement<THumanTaskData> createHumanTaskData(THumanTaskData value) {
        return new JAXBElement<THumanTaskData>(_HumanTaskData_QNAME, THumanTaskData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://decidr.de/schema/humanTask", name = "content")
    public JAXBElement<TContent> createContent(TContent value) {
        return new JAXBElement<TContent>(_Content_QNAME, TContent.class, null, value);
    }

}
