//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.07 at 09:21:14 PM MEZ 
//

package de.decidr.model.workflowmodel.bpel;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for tAssign complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tAssign">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tActivity">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}copy"/>
 *           &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}extensionAssignOperation"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="validate" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tBoolean" default="no" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAssign", propOrder = { "copyOrExtensionAssignOperation" })
public class Assign extends Activity {

    @XmlElements( {
            @XmlElement(name = "copy", type = Copy.class),
            @XmlElement(name = "extensionAssignOperation", type = ExtensionAssignOperation.class) })
    protected List<ExtensibleElements> copyOrExtensionAssignOperation;
    @XmlAttribute
    protected Boolean validate;

    /**
     * Gets the value of the copyOrExtensionAssignOperation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the copyOrExtensionAssignOperation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getCopyOrExtensionAssignOperation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Copy }
     * {@link ExtensionAssignOperation }
     * 
     * 
     */
    public List<ExtensibleElements> getCopyOrExtensionAssignOperation() {
        if (copyOrExtensionAssignOperation == null) {
            copyOrExtensionAssignOperation = new ArrayList<ExtensibleElements>();
        }
        return this.copyOrExtensionAssignOperation;
    }

    public boolean isSetCopyOrExtensionAssignOperation() {
        return ((this.copyOrExtensionAssignOperation != null) && (!this.copyOrExtensionAssignOperation
                .isEmpty()));
    }

    public void unsetCopyOrExtensionAssignOperation() {
        this.copyOrExtensionAssignOperation = null;
    }

    /**
     * Gets the value of the validate property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getValidate() {
        if (validate == null) {
            return Boolean.NO;
        } else {
            return validate;
        }
    }

    /**
     * Sets the value of the validate property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setValidate(Boolean value) {
        this.validate = value;
    }

    public boolean isSetValidate() {
        return (this.validate != null);
    }

}
