//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.06 at 10:48:46 AM MESZ 
//


package de.decidr.model.workflowmodel.bpel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tElseif complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tElseif">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}condition"/>
 *         &lt;group ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}activity"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tElseif", propOrder = {
    "condition",
    "assign",
    "compensate",
    "compensateScope",
    "empty",
    "exit",
    "extensionActivity",
    "flow",
    "forEach",
    "_if",
    "invoke",
    "pick",
    "receive",
    "repeatUntil",
    "reply",
    "rethrow",
    "scope",
    "sequence",
    "_throw",
    "validate",
    "wait",
    "_while"
})
public class Elseif
    extends ExtensibleElements
{

    @XmlElement(required = true)
    protected BooleanExpression condition;
    protected Assign assign;
    protected Compensate compensate;
    protected CompensateScope compensateScope;
    protected Empty empty;
    protected Exit exit;
    protected ExtensionActivity extensionActivity;
    protected Flow flow;
    protected ForEach forEach;
    @XmlElement(name = "if")
    protected If _if;
    protected Invoke invoke;
    protected Pick pick;
    protected Receive receive;
    protected RepeatUntil repeatUntil;
    protected Reply reply;
    protected Rethrow rethrow;
    protected Scope scope;
    protected Sequence sequence;
    @XmlElement(name = "throw")
    protected Throw _throw;
    protected Validate validate;
    protected Wait wait;
    @XmlElement(name = "while")
    protected While _while;

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanExpression }
     *     
     */
    public BooleanExpression getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanExpression }
     *     
     */
    public void setCondition(BooleanExpression value) {
        this.condition = value;
    }

    public boolean isSetCondition() {
        return (this.condition!= null);
    }

    /**
     * Gets the value of the assign property.
     * 
     * @return
     *     possible object is
     *     {@link Assign }
     *     
     */
    public Assign getAssign() {
        return assign;
    }

    /**
     * Sets the value of the assign property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assign }
     *     
     */
    public void setAssign(Assign value) {
        this.assign = value;
    }

    public boolean isSetAssign() {
        return (this.assign!= null);
    }

    /**
     * Gets the value of the compensate property.
     * 
     * @return
     *     possible object is
     *     {@link Compensate }
     *     
     */
    public Compensate getCompensate() {
        return compensate;
    }

    /**
     * Sets the value of the compensate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Compensate }
     *     
     */
    public void setCompensate(Compensate value) {
        this.compensate = value;
    }

    public boolean isSetCompensate() {
        return (this.compensate!= null);
    }

    /**
     * Gets the value of the compensateScope property.
     * 
     * @return
     *     possible object is
     *     {@link CompensateScope }
     *     
     */
    public CompensateScope getCompensateScope() {
        return compensateScope;
    }

    /**
     * Sets the value of the compensateScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensateScope }
     *     
     */
    public void setCompensateScope(CompensateScope value) {
        this.compensateScope = value;
    }

    public boolean isSetCompensateScope() {
        return (this.compensateScope!= null);
    }

    /**
     * Gets the value of the empty property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getEmpty() {
        return empty;
    }

    /**
     * Sets the value of the empty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setEmpty(Empty value) {
        this.empty = value;
    }

    public boolean isSetEmpty() {
        return (this.empty!= null);
    }

    /**
     * Gets the value of the exit property.
     * 
     * @return
     *     possible object is
     *     {@link Exit }
     *     
     */
    public Exit getExit() {
        return exit;
    }

    /**
     * Sets the value of the exit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Exit }
     *     
     */
    public void setExit(Exit value) {
        this.exit = value;
    }

    public boolean isSetExit() {
        return (this.exit!= null);
    }

    /**
     * Gets the value of the extensionActivity property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionActivity }
     *     
     */
    public ExtensionActivity getExtensionActivity() {
        return extensionActivity;
    }

    /**
     * Sets the value of the extensionActivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionActivity }
     *     
     */
    public void setExtensionActivity(ExtensionActivity value) {
        this.extensionActivity = value;
    }

    public boolean isSetExtensionActivity() {
        return (this.extensionActivity!= null);
    }

    /**
     * Gets the value of the flow property.
     * 
     * @return
     *     possible object is
     *     {@link Flow }
     *     
     */
    public Flow getFlow() {
        return flow;
    }

    /**
     * Sets the value of the flow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flow }
     *     
     */
    public void setFlow(Flow value) {
        this.flow = value;
    }

    public boolean isSetFlow() {
        return (this.flow!= null);
    }

    /**
     * Gets the value of the forEach property.
     * 
     * @return
     *     possible object is
     *     {@link ForEach }
     *     
     */
    public ForEach getForEach() {
        return forEach;
    }

    /**
     * Sets the value of the forEach property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForEach }
     *     
     */
    public void setForEach(ForEach value) {
        this.forEach = value;
    }

    public boolean isSetForEach() {
        return (this.forEach!= null);
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link If }
     *     
     */
    public If getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link If }
     *     
     */
    public void setIf(If value) {
        this._if = value;
    }

    public boolean isSetIf() {
        return (this._if!= null);
    }

    /**
     * Gets the value of the invoke property.
     * 
     * @return
     *     possible object is
     *     {@link Invoke }
     *     
     */
    public Invoke getInvoke() {
        return invoke;
    }

    /**
     * Sets the value of the invoke property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoke }
     *     
     */
    public void setInvoke(Invoke value) {
        this.invoke = value;
    }

    public boolean isSetInvoke() {
        return (this.invoke!= null);
    }

    /**
     * Gets the value of the pick property.
     * 
     * @return
     *     possible object is
     *     {@link Pick }
     *     
     */
    public Pick getPick() {
        return pick;
    }

    /**
     * Sets the value of the pick property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pick }
     *     
     */
    public void setPick(Pick value) {
        this.pick = value;
    }

    public boolean isSetPick() {
        return (this.pick!= null);
    }

    /**
     * Gets the value of the receive property.
     * 
     * @return
     *     possible object is
     *     {@link Receive }
     *     
     */
    public Receive getReceive() {
        return receive;
    }

    /**
     * Sets the value of the receive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Receive }
     *     
     */
    public void setReceive(Receive value) {
        this.receive = value;
    }

    public boolean isSetReceive() {
        return (this.receive!= null);
    }

    /**
     * Gets the value of the repeatUntil property.
     * 
     * @return
     *     possible object is
     *     {@link RepeatUntil }
     *     
     */
    public RepeatUntil getRepeatUntil() {
        return repeatUntil;
    }

    /**
     * Sets the value of the repeatUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepeatUntil }
     *     
     */
    public void setRepeatUntil(RepeatUntil value) {
        this.repeatUntil = value;
    }

    public boolean isSetRepeatUntil() {
        return (this.repeatUntil!= null);
    }

    /**
     * Gets the value of the reply property.
     * 
     * @return
     *     possible object is
     *     {@link Reply }
     *     
     */
    public Reply getReply() {
        return reply;
    }

    /**
     * Sets the value of the reply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reply }
     *     
     */
    public void setReply(Reply value) {
        this.reply = value;
    }

    public boolean isSetReply() {
        return (this.reply!= null);
    }

    /**
     * Gets the value of the rethrow property.
     * 
     * @return
     *     possible object is
     *     {@link Rethrow }
     *     
     */
    public Rethrow getRethrow() {
        return rethrow;
    }

    /**
     * Sets the value of the rethrow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rethrow }
     *     
     */
    public void setRethrow(Rethrow value) {
        this.rethrow = value;
    }

    public boolean isSetRethrow() {
        return (this.rethrow!= null);
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link Scope }
     *     
     */
    public Scope getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scope }
     *     
     */
    public void setScope(Scope value) {
        this.scope = value;
    }

    public boolean isSetScope() {
        return (this.scope!= null);
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link Sequence }
     *     
     */
    public Sequence getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sequence }
     *     
     */
    public void setSequence(Sequence value) {
        this.sequence = value;
    }

    public boolean isSetSequence() {
        return (this.sequence!= null);
    }

    /**
     * Gets the value of the throw property.
     * 
     * @return
     *     possible object is
     *     {@link Throw }
     *     
     */
    public Throw getThrow() {
        return _throw;
    }

    /**
     * Sets the value of the throw property.
     * 
     * @param value
     *     allowed object is
     *     {@link Throw }
     *     
     */
    public void setThrow(Throw value) {
        this._throw = value;
    }

    public boolean isSetThrow() {
        return (this._throw!= null);
    }

    /**
     * Gets the value of the validate property.
     * 
     * @return
     *     possible object is
     *     {@link Validate }
     *     
     */
    public Validate getValidate() {
        return validate;
    }

    /**
     * Sets the value of the validate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Validate }
     *     
     */
    public void setValidate(Validate value) {
        this.validate = value;
    }

    public boolean isSetValidate() {
        return (this.validate!= null);
    }

    /**
     * Gets the value of the wait property.
     * 
     * @return
     *     possible object is
     *     {@link Wait }
     *     
     */
    public Wait getWait() {
        return wait;
    }

    /**
     * Sets the value of the wait property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wait }
     *     
     */
    public void setWait(Wait value) {
        this.wait = value;
    }

    public boolean isSetWait() {
        return (this.wait!= null);
    }

    /**
     * Gets the value of the while property.
     * 
     * @return
     *     possible object is
     *     {@link While }
     *     
     */
    public While getWhile() {
        return _while;
    }

    /**
     * Sets the value of the while property.
     * 
     * @param value
     *     allowed object is
     *     {@link While }
     *     
     */
    public void setWhile(While value) {
        this._while = value;
    }

    public boolean isSetWhile() {
        return (this._while!= null);
    }

}
