//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.07 at 09:21:14 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/wsbpel/2.0/process/executable", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.decidr.model.workflowmodel.bpel;
