//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.07 at 09:21:14 PM MEZ 
//

package de.decidr.model.workflowmodel.bpel;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * XSD Authors: The child element onAlarm needs to be a Local Element
 * Declaration, because there is another onAlarm element defined for event
 * handlers.
 * 
 * 
 * <p>
 * Java class for tPick complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tPick">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tActivity">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}onMessage" maxOccurs="unbounded"/>
 *         &lt;element name="onAlarm" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tOnAlarmPick" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="createInstance" type="{http://docs.oasis-open.org/wsbpel/2.0/process/executable}tBoolean" default="no" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tPick", propOrder = { "onMessage", "onAlarm" })
public class Pick extends Activity {

    @XmlElement(required = true)
    protected List<OnMessage> onMessage;
    protected List<OnAlarmPick> onAlarm;
    @XmlAttribute
    protected Boolean createInstance;

    /**
     * Gets the value of the onMessage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the onMessage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOnMessage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnMessage }
     * 
     * 
     */
    public List<OnMessage> getOnMessage() {
        if (onMessage == null) {
            onMessage = new ArrayList<OnMessage>();
        }
        return this.onMessage;
    }

    public boolean isSetOnMessage() {
        return ((this.onMessage != null) && (!this.onMessage.isEmpty()));
    }

    public void unsetOnMessage() {
        this.onMessage = null;
    }

    /**
     * Gets the value of the onAlarm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the onAlarm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOnAlarm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OnAlarmPick }
     * 
     * 
     */
    public List<OnAlarmPick> getOnAlarm() {
        if (onAlarm == null) {
            onAlarm = new ArrayList<OnAlarmPick>();
        }
        return this.onAlarm;
    }

    public boolean isSetOnAlarm() {
        return ((this.onAlarm != null) && (!this.onAlarm.isEmpty()));
    }

    public void unsetOnAlarm() {
        this.onAlarm = null;
    }

    /**
     * Gets the value of the createInstance property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean getCreateInstance() {
        if (createInstance == null) {
            return Boolean.NO;
        } else {
            return createInstance;
        }
    }

    /**
     * Sets the value of the createInstance property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setCreateInstance(Boolean value) {
        this.createInstance = value;
    }

    public boolean isSetCreateInstance() {
        return (this.createInstance != null);
    }

}
