/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Login generated by hbm2java.
 */
public class Login implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private Long id;

    /** The user. */
    private User user;

    /** The login date. */
    private Date loginDate;

    /** The success. */
    private boolean success;

    /**
     * Instantiates a new login.
     */
    public Login() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new login.
     * 
     * @param user
     *            the user
     * @param loginDate
     *            the login date
     * @param success
     *            the success
     */
    public Login(User user, Date loginDate, boolean success) {
        // generated full constructor
        this.user = user;
        this.loginDate = loginDate;
        this.success = success;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Gets the login date.
     * 
     * @return the login date
     */
    public Date getLoginDate() {
        return this.loginDate;
    }

    /**
     * Gets the user.
     * 
     * @return the user
     */
    public User getUser() {
        return this.user;
    }

    /**
     * Checks if is success.
     * 
     * @return true, if is success
     */
    public boolean isSuccess() {
        return this.success;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Sets the login date.
     * 
     * @param loginDate
     *            the new login date
     */
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    /**
     * Sets the success.
     * 
     * @param success
     *            the new success
     */
    public void setSuccess(boolean success) {
        this.success = success;
    }

    /**
     * Sets the user.
     * 
     * @param user
     *            the new user
     */
    public void setUser(User user) {
        this.user = user;
    }

}
