/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

/**
 * RoleHasPermission generated by hbm2java.
 */
public class RoleHasPermission implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private RoleHasPermissionId id;

    /** The role. */
    private Role role;

    /** The permission. */
    private Permission permission;

    /**
     * Instantiates a new role has permission.
     */
    public RoleHasPermission() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new role has permission.
     * 
     * @param id
     *            the id
     * @param role
     *            the role
     * @param permission
     *            the permission
     */
    public RoleHasPermission(RoleHasPermissionId id, Role role,
            Permission permission) {
        // generated full constructor
        this.id = id;
        this.role = role;
        this.permission = permission;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public RoleHasPermissionId getId() {
        return this.id;
    }

    /**
     * Gets the permission.
     * 
     * @return the permission
     */
    public Permission getPermission() {
        return this.permission;
    }

    /**
     * Gets the role.
     * 
     * @return the role
     */
    public Role getRole() {
        return this.role;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(RoleHasPermissionId id) {
        this.id = id;
    }

    /**
     * Sets the permission.
     * 
     * @param permission
     *            the new permission
     */
    public void setPermission(Permission permission) {
        this.permission = permission;
    }

    /**
     * Sets the role.
     * 
     * @param role
     *            the new role
     */
    public void setRole(Role role) {
        this.role = role;
    }

}
