/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * WorkItemSummaryView generated by hbm2java.
 */
public class WorkItemSummaryView implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private long id;

    /** The work item name. */
    private String workItemName;

    /** The tenant name. */
    private String tenantName;

    /** The creation date. */
    private Date creationDate;

    /** The work item status. */
    private String workItemStatus;

    /** The user id. */
    private long userId;

    /** The workflow instance id. */
    private long workflowInstanceId;

    /**
     * Instantiates a new work item summary view.
     */
    public WorkItemSummaryView() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new work item summary view.
     * 
     * @param id
     *            the id
     * @param workItemName
     *            the work item name
     * @param tenantName
     *            the tenant name
     * @param creationDate
     *            the creation date
     * @param workItemStatus
     *            the work item status
     * @param userId
     *            the user id
     * @param workflowInstanceId
     *            the workflow instance id
     */
    public WorkItemSummaryView(long id, String workItemName, String tenantName,
            Date creationDate, String workItemStatus, long userId,
            long workflowInstanceId) {
        // generated full constructor
        this.id = id;
        this.workItemName = workItemName;
        this.tenantName = tenantName;
        this.creationDate = creationDate;
        this.workItemStatus = workItemStatus;
        this.userId = userId;
        this.workflowInstanceId = workflowInstanceId;
    }

    /**
     * Gets the creation date.
     * 
     * @return the creation date
     */
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public long getId() {
        return this.id;
    }

    /**
     * Gets the tenant name.
     * 
     * @return the tenant name
     */
    public String getTenantName() {
        return this.tenantName;
    }

    /**
     * Gets the user id.
     * 
     * @return the user id
     */
    public long getUserId() {
        return this.userId;
    }

    /**
     * Gets the workflow instance id.
     * 
     * @return the workflow instance id
     */
    public long getWorkflowInstanceId() {
        return this.workflowInstanceId;
    }

    /**
     * Gets the work item name.
     * 
     * @return the work item name
     */
    public String getWorkItemName() {
        return this.workItemName;
    }

    /**
     * Gets the work item status.
     * 
     * @return the work item status
     */
    public String getWorkItemStatus() {
        return this.workItemStatus;
    }

    /**
     * Sets the creation date.
     * 
     * @param creationDate
     *            the new creation date
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Sets the tenant name.
     * 
     * @param tenantName
     *            the new tenant name
     */
    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    /**
     * Sets the user id.
     * 
     * @param userId
     *            the new user id
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * Sets the workflow instance id.
     * 
     * @param workflowInstanceId
     *            the new workflow instance id
     */
    public void setWorkflowInstanceId(long workflowInstanceId) {
        this.workflowInstanceId = workflowInstanceId;
    }

    /**
     * Sets the work item name.
     * 
     * @param workItemName
     *            the new work item name
     */
    public void setWorkItemName(String workItemName) {
        this.workItemName = workItemName;
    }

    /**
     * Sets the work item status.
     * 
     * @param workItemStatus
     *            the new work item status
     */
    public void setWorkItemStatus(String workItemStatus) {
        this.workItemStatus = workItemStatus;
    }

}
