/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package de.decidr.odemonitor.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1 RR document
 */
@WebService(name = "ODEMonitorPT", targetNamespace = "http://decidr.de/webservices/ODEMonitor")
@XmlSeeAlso( { ObjectFactory.class })
public interface ODEMonitorService {

    public static final String TARGET_NAMESPACE = "http://decidr.de/webservices/ODEMonitor";
    public static final String SERVICE_NAME = "ODEMonitor";
    public static final QName SERVICE = new QName(
    "http://decidr.de/webservices/ODEMonitor", SERVICE_NAME);
    public static final QName ENDPOINT = new QName(TARGET_NAMESPACE,
    "ODEMonitorSOAP");

    /**
     * RR document
     * 
     * @param wfModels
     * @param odeID
     * @param run
     * @param configVersion
     * @param wfInstances
     */
    @WebMethod(action = "http://decidr.de/webservices/ODEMonitor/updateStats")
    @RequestWrapper(localName = "updateStats", targetNamespace = "http://decidr.de/webservices/ODEMonitor", className = "de.decidr.webservices.odemonitor.UpdateStats")
    @ResponseWrapper(localName = "updateStatsResponse", targetNamespace = "http://decidr.de/webservices/ODEMonitor", className = "de.decidr.webservices.odemonitor.UpdateStatsResponse")
    public void updateStats(
            @WebParam(name = "wfInstances", targetNamespace = "") int wfInstances,
            @WebParam(name = "wfModels", targetNamespace = "") int wfModels,
            @WebParam(name = "odeID", targetNamespace = "") String odeID,
            @WebParam(name = "configVersion", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<XMLGregorianCalendar> configVersion,
            @WebParam(name = "run", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<Boolean> run);

    /**
     * RR document
     * 
     * @param poolInstance
     * @return returns java.lang.String
     */
    @WebMethod(action = "http://decidr.de/webservices/ODEMonitor/registerODE")
    @WebResult(name = "odeID", targetNamespace = "")
    @RequestWrapper(localName = "registerODE", targetNamespace = "http://decidr.de/webservices/ODEMonitor", className = "de.decidr.webservices.odemonitor.RegisterODE")
    @ResponseWrapper(localName = "registerODEResponse", targetNamespace = "http://decidr.de/webservices/ODEMonitor", className = "de.decidr.webservices.odemonitor.RegisterODEResponse")
    public String registerODE(
            @WebParam(name = "poolInstance", targetNamespace = "") boolean poolInstance);

    /**
     * RR document
     * 
     * @param configChanged
     * @param updateInterval
     */
    @WebMethod(action = "http://decidr.de/webservices/ODEMonitor/getConfig")
    @RequestWrapper(localName = "getConfig", targetNamespace = "http://decidr.de/webservices/ODEMonitor", className = "de.decidr.webservices.odemonitor.GetConfig")
    @ResponseWrapper(localName = "getConfigResponse", targetNamespace = "http://decidr.de/webservices/ODEMonitor", className = "de.decidr.webservices.odemonitor.GetConfigResponse")
    public void getConfig(
            @WebParam(name = "updateInterval", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<Integer> updateInterval,
            @WebParam(name = "configChanged", targetNamespace = "", mode = WebParam.Mode.OUT) Holder<XMLGregorianCalendar> configChanged);
}
