function de_decidr_ui_view_MainWidgetset(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',r='/',ub='<script defer="defer">de_decidr_ui_view_MainWidgetset.onInjectionDone(\'de.decidr.ui.view.MainWidgetset\')<\/script>',zb='<script id="',A='=',q='?',C='Bad handler "',tb='DOMContentLoaded',ib='F847C22FC38D9EB7BEEA3AB79D1E3B80.cache.html',rb='ModelingToolWidget.css',o='SCRIPT',yb='__gwt_marker_de.decidr.ui.view.MainWidgetset',s='base',nb='begin',cb='bootstrap',u='clear.cache.gif',z='content',sb='css/ext-all.css',m='de.decidr.ui.view.MainWidgetset',xb='end',jb='gwt-dnd.css',vb='gwt.hybrid',qb='gwt/standard/standard.css',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',pb='head',gb='hosted.html?de_decidr_ui_view_MainWidgetset',ob='href',ab='iframe',t='img',bb="javascript:''",kb='link',fb='loadExternalRefs',v='meta',eb='moduleRequested',wb='moduleStartup',w='name',db='position:absolute;width:0;height:0;border:none',lb='rel',hb='selectingPermutation',x='startup',mb='stylesheet';var Bb=window,k=document,Ab=Bb.__gwtStatsEvent?function(a){return Bb.__gwtStatsEvent(a)}:null,pc,fc,ac,Fb=l,ic={},sc=[],oc=[],Eb=[],lc,nc;Ab&&Ab({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!Bb.__gwt_stylesLoaded){Bb.__gwt_stylesLoaded={}}if(!Bb.__gwt_scriptsLoaded){Bb.__gwt_scriptsLoaded={}}function ec(){var b=false;try{b=Bb.external&&(Bb.external.gwtOnLoad&&Bb.location.search.indexOf(vb)==-1)}catch(a){}ec=function(){return b};return b}
function hc(){if(pc&&fc){var c=k.getElementById(m);var b=c.contentWindow;if(ec()){b.__gwt_getProperty=function(a){return bc(a)}}de_decidr_ui_view_MainWidgetset=null;b.gwtOnLoad(lc,m,Fb);Ab&&Ab({moduleName:m,subSystem:x,evtGroup:wb,millis:(new Date()).getTime(),type:xb})}}
function cc(){var j,h=yb,i;k.write(zb+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){Fb=f(j.src)}if(Fb==l){var e=k.getElementsByTagName(s);if(e.length>0){Fb=e[e.length-1].href}else{Fb=f(k.location.href)}}else if(Fb.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=Fb+u;Fb=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function mc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}ic[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{nc=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{lc=eval(b)}catch(a){alert(C+b+F)}}}}}}
function bc(d){var e=oc[d](),b=sc[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(nc){nc(d,a,e)}throw null}
var dc;function gc(){if(!dc){dc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);Ab&&Ab({moduleName:m,subSystem:x,evtGroup:wb,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(Fb+qc)}}
de_decidr_ui_view_MainWidgetset.onScriptLoad=function(){if(dc){fc=true;hc()}};de_decidr_ui_view_MainWidgetset.onInjectionDone=function(){pc=true;Ab&&Ab({moduleName:m,subSystem:x,evtGroup:fb,millis:(new Date()).getTime(),type:xb});hc()};cc();var qc;if(ec()){if(Bb.external.initModule&&Bb.external.initModule(m)){Bb.location.reload();return}qc=gb}mc();Ab&&Ab({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:hb});if(!qc){try{qc=ib}catch(a){return}}var kc;function jc(){if(!ac){ac=true;if(!__gwt_stylesLoaded[jb]){var a=k.createElement(kb);__gwt_stylesLoaded[jb]=a;a.setAttribute(lb,mb);a.setAttribute(ob,Fb+jb);k.getElementsByTagName(pb)[0].appendChild(a)}if(!__gwt_stylesLoaded[qb]){var a=k.createElement(kb);__gwt_stylesLoaded[qb]=a;a.setAttribute(lb,mb);a.setAttribute(ob,Fb+qb);k.getElementsByTagName(pb)[0].appendChild(a)}if(!__gwt_stylesLoaded[rb]){var a=k.createElement(kb);__gwt_stylesLoaded[rb]=a;a.setAttribute(lb,mb);a.setAttribute(ob,Fb+rb);k.getElementsByTagName(pb)[0].appendChild(a)}if(!__gwt_stylesLoaded[sb]){var a=k.createElement(kb);__gwt_stylesLoaded[sb]=a;a.setAttribute(lb,mb);a.setAttribute(ob,Fb+sb);k.getElementsByTagName(pb)[0].appendChild(a)}hc();if(k.removeEventListener){k.removeEventListener(tb,jc,false)}if(kc){clearInterval(kc)}}}
if(k.addEventListener){k.addEventListener(tb,function(){gc();jc()},false)}var kc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){gc();jc()}},50);Ab&&Ab({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:xb});Ab&&Ab({moduleName:m,subSystem:x,evtGroup:fb,millis:(new Date()).getTime(),type:nb});k.write(ub)}
de_decidr_ui_view_MainWidgetset();