package de.decidr.model.entities;

// Generated 04.05.2009 13:48:05 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DeployedWorkflowModel generated by hbm2java
 */
public class DeployedWorkflowModel implements java.io.Serializable {

	private Long id;
	private long version;
	private WorkflowModel originalWorkflowModel;
	private Tenant tenant;
	private Server deployedOnServer;
	private String name;
	private String description;
	private byte[] dwdl;
	private byte[] wsdl;
	private byte[] soapTemplate;
	private Date deployDate;
	private long odeVersion;
	private Set<StartConfiguration> startConfigurations = new HashSet<StartConfiguration>(
			0);
	private Set<WorkflowInstance> workflowInstances = new HashSet<WorkflowInstance>(
			0);

	public DeployedWorkflowModel() {
	}

	public DeployedWorkflowModel(Tenant tenant, Server deployedOnServer,
			String name, String description, byte[] dwdl, byte[] wsdl,
			byte[] soapTemplate, Date deployDate, long odeVersion) {
		this.tenant = tenant;
		this.deployedOnServer = deployedOnServer;
		this.name = name;
		this.description = description;
		this.dwdl = dwdl;
		this.wsdl = wsdl;
		this.soapTemplate = soapTemplate;
		this.deployDate = deployDate;
		this.odeVersion = odeVersion;
	}

	public DeployedWorkflowModel(WorkflowModel originalWorkflowModel,
			Tenant tenant, Server deployedOnServer, String name,
			String description, byte[] dwdl, byte[] wsdl, byte[] soapTemplate,
			Date deployDate, long odeVersion,
			Set<StartConfiguration> startConfigurations,
			Set<WorkflowInstance> workflowInstances) {
		this.originalWorkflowModel = originalWorkflowModel;
		this.tenant = tenant;
		this.deployedOnServer = deployedOnServer;
		this.name = name;
		this.description = description;
		this.dwdl = dwdl;
		this.wsdl = wsdl;
		this.soapTemplate = soapTemplate;
		this.deployDate = deployDate;
		this.odeVersion = odeVersion;
		this.startConfigurations = startConfigurations;
		this.workflowInstances = workflowInstances;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getVersion() {
		return this.version;
	}

	public void setVersion(long version) {
		this.version = version;
	}

	public WorkflowModel getOriginalWorkflowModel() {
		return this.originalWorkflowModel;
	}

	public void setOriginalWorkflowModel(WorkflowModel originalWorkflowModel) {
		this.originalWorkflowModel = originalWorkflowModel;
	}

	public Tenant getTenant() {
		return this.tenant;
	}

	public void setTenant(Tenant tenant) {
		this.tenant = tenant;
	}

	public Server getDeployedOnServer() {
		return this.deployedOnServer;
	}

	public void setDeployedOnServer(Server deployedOnServer) {
		this.deployedOnServer = deployedOnServer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getDwdl() {
		return this.dwdl;
	}

	public void setDwdl(byte[] dwdl) {
		this.dwdl = dwdl;
	}

	public byte[] getWsdl() {
		return this.wsdl;
	}

	public void setWsdl(byte[] wsdl) {
		this.wsdl = wsdl;
	}

	public byte[] getSoapTemplate() {
		return this.soapTemplate;
	}

	public void setSoapTemplate(byte[] soapTemplate) {
		this.soapTemplate = soapTemplate;
	}

	public Date getDeployDate() {
		return this.deployDate;
	}

	public void setDeployDate(Date deployDate) {
		this.deployDate = deployDate;
	}

	public long getOdeVersion() {
		return this.odeVersion;
	}

	public void setOdeVersion(long odeVersion) {
		this.odeVersion = odeVersion;
	}

	public Set<StartConfiguration> getStartConfigurations() {
		return this.startConfigurations;
	}

	public void setStartConfigurations(
			Set<StartConfiguration> startConfigurations) {
		this.startConfigurations = startConfigurations;
	}

	public Set<WorkflowInstance> getWorkflowInstances() {
		return this.workflowInstances;
	}

	public void setWorkflowInstances(Set<WorkflowInstance> workflowInstances) {
		this.workflowInstances = workflowInstances;
	}

}
