package de.decidr.model.entities;

// Generated 04.05.2009 13:48:05 by Hibernate Tools 3.2.2.GA

/**
 * KnownWebService generated by hbm2java
 */
public class KnownWebService implements java.io.Serializable {

	private Long id;
	private String name;
	private byte[] wsdl;

	public KnownWebService() {
	}

	public KnownWebService(String name, byte[] wsdl) {
		this.name = name;
		this.wsdl = wsdl;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getWsdl() {
		return this.wsdl;
	}

	public void setWsdl(byte[] wsdl) {
		this.wsdl = wsdl;
	}

}
