package de.decidr.model.entities;

// Generated 04.05.2009 13:48:05 by Hibernate Tools 3.2.2.GA

/**
 * ServerLoadViewId generated by hbm2java
 */
public class ServerLoadViewId implements java.io.Serializable {

	private long id;
	private byte load;
	private long numInstances;

	public ServerLoadViewId() {
	}

	public ServerLoadViewId(long id, byte load, long numInstances) {
		this.id = id;
		this.load = load;
		this.numInstances = numInstances;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public byte getLoad() {
		return this.load;
	}

	public void setLoad(byte load) {
		this.load = load;
	}

	public long getNumInstances() {
		return this.numInstances;
	}

	public void setNumInstances(long numInstances) {
		this.numInstances = numInstances;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServerLoadViewId))
			return false;
		ServerLoadViewId castOther = (ServerLoadViewId) other;

		return (this.getId() == castOther.getId())
				&& (this.getLoad() == castOther.getLoad())
				&& (this.getNumInstances() == castOther.getNumInstances());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + this.getLoad();
		result = 37 * result + (int) this.getNumInstances();
		return result;
	}

}
