//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.26 at 12:15:57 PM GMT+01:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://decidr.de/schema/wsc", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.decidr.model.workflowmodel.wsc;
