/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 28.12.2009 10:39:25 by Hibernate Tools 3.2.4.GA

/**
 * Activity generated by hbm2java.
 */
public class Activity implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private Long id;

    /** The known web service. */
    private KnownWebService knownWebService;

    /** The mapping. */
    private byte[] mapping;

    /** The name. */
    private String name;

    /**
     * Instantiates a new activity.
     */
    public Activity() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new activity.
     * 
     * @param knownWebService
     *            the known web service
     * @param mapping
     *            the mapping
     * @param name
     *            the name
     */
    public Activity(KnownWebService knownWebService, byte[] mapping, String name) {
        // generated full constructor
        this.knownWebService = knownWebService;
        this.mapping = mapping;
        this.name = name;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the known web service.
     * 
     * @return the known web service
     */
    public KnownWebService getKnownWebService() {
        return this.knownWebService;
    }

    /**
     * Sets the known web service.
     * 
     * @param knownWebService
     *            the new known web service
     */
    public void setKnownWebService(KnownWebService knownWebService) {
        this.knownWebService = knownWebService;
    }

    /**
     * Gets the mapping.
     * 
     * @return the mapping
     */
    public byte[] getMapping() {
        return this.mapping;
    }

    /**
     * Sets the mapping.
     * 
     * @param mapping
     *            the new mapping
     */
    public void setMapping(byte[] mapping) {
        this.mapping = mapping;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the name.
     * 
     * @param name
     *            the new name
     */
    public void setName(String name) {
        this.name = name;
    }

}
