/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 28.12.2009 10:39:25 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DeployedWorkflowModel generated by hbm2java.
 */
public class DeployedWorkflowModel implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private Long id;

    /** The original workflow model. */
    private WorkflowModel originalWorkflowModel;

    /** The tenant. */
    private Tenant tenant;

    /** The name. */
    private String name;

    /** The description. */
    private String description;

    /** The dwdl. */
    private byte[] dwdl;

    /** The wsdl. */
    private byte[] wsdl;

    /** The soap template. */
    private byte[] soapTemplate;

    /** The deploy date. */
    private Date deployDate;

    /** The version. */
    private long version;

    /** The workflow model is deployed on servers. */
    private Set<WorkflowModelIsDeployedOnServer> workflowModelIsDeployedOnServers = new HashSet<WorkflowModelIsDeployedOnServer>(
            0);

    /** The start configurations. */
    private Set<StartConfiguration> startConfigurations = new HashSet<StartConfiguration>(
            0);

    /** The workflow instances. */
    private Set<WorkflowInstance> workflowInstances = new HashSet<WorkflowInstance>(
            0);

    /**
     * Instantiates a new deployed workflow model.
     */
    public DeployedWorkflowModel() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new deployed workflow model.
     * 
     * @param tenant
     *            the tenant
     * @param name
     *            the name
     * @param description
     *            the description
     * @param dwdl
     *            the dwdl
     * @param wsdl
     *            the wsdl
     * @param soapTemplate
     *            the soap template
     * @param deployDate
     *            the deploy date
     * @param version
     *            the version
     */
    public DeployedWorkflowModel(Tenant tenant, String name,
            String description, byte[] dwdl, byte[] wsdl, byte[] soapTemplate,
            Date deployDate, long version) {
        // generated minimal constructor
        this.tenant = tenant;
        this.name = name;
        this.description = description;
        this.dwdl = dwdl;
        this.wsdl = wsdl;
        this.soapTemplate = soapTemplate;
        this.deployDate = deployDate;
        this.version = version;
    }

    /**
     * Instantiates a new deployed workflow model.
     * 
     * @param originalWorkflowModel
     *            the original workflow model
     * @param tenant
     *            the tenant
     * @param name
     *            the name
     * @param description
     *            the description
     * @param dwdl
     *            the dwdl
     * @param wsdl
     *            the wsdl
     * @param soapTemplate
     *            the soap template
     * @param deployDate
     *            the deploy date
     * @param version
     *            the version
     * @param workflowModelIsDeployedOnServers
     *            the workflow model is deployed on servers
     * @param startConfigurations
     *            the start configurations
     * @param workflowInstances
     *            the workflow instances
     */
    public DeployedWorkflowModel(
            WorkflowModel originalWorkflowModel,
            Tenant tenant,
            String name,
            String description,
            byte[] dwdl,
            byte[] wsdl,
            byte[] soapTemplate,
            Date deployDate,
            long version,
            Set<WorkflowModelIsDeployedOnServer> workflowModelIsDeployedOnServers,
            Set<StartConfiguration> startConfigurations,
            Set<WorkflowInstance> workflowInstances) {
        // generated full constructor
        this.originalWorkflowModel = originalWorkflowModel;
        this.tenant = tenant;
        this.name = name;
        this.description = description;
        this.dwdl = dwdl;
        this.wsdl = wsdl;
        this.soapTemplate = soapTemplate;
        this.deployDate = deployDate;
        this.version = version;
        this.workflowModelIsDeployedOnServers = workflowModelIsDeployedOnServers;
        this.startConfigurations = startConfigurations;
        this.workflowInstances = workflowInstances;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the original workflow model.
     * 
     * @return the original workflow model
     */
    public WorkflowModel getOriginalWorkflowModel() {
        return this.originalWorkflowModel;
    }

    /**
     * Sets the original workflow model.
     * 
     * @param originalWorkflowModel
     *            the new original workflow model
     */
    public void setOriginalWorkflowModel(WorkflowModel originalWorkflowModel) {
        this.originalWorkflowModel = originalWorkflowModel;
    }

    /**
     * Gets the tenant.
     * 
     * @return the tenant
     */
    public Tenant getTenant() {
        return this.tenant;
    }

    /**
     * Sets the tenant.
     * 
     * @param tenant
     *            the new tenant
     */
    public void setTenant(Tenant tenant) {
        this.tenant = tenant;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the name.
     * 
     * @param name
     *            the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the description.
     * 
     * @return the description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the description.
     * 
     * @param description
     *            the new description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the dwdl.
     * 
     * @return the dwdl
     */
    public byte[] getDwdl() {
        return this.dwdl;
    }

    /**
     * Sets the dwdl.
     * 
     * @param dwdl
     *            the new dwdl
     */
    public void setDwdl(byte[] dwdl) {
        this.dwdl = dwdl;
    }

    /**
     * Gets the wsdl.
     * 
     * @return the wsdl
     */
    public byte[] getWsdl() {
        return this.wsdl;
    }

    /**
     * Sets the wsdl.
     * 
     * @param wsdl
     *            the new wsdl
     */
    public void setWsdl(byte[] wsdl) {
        this.wsdl = wsdl;
    }

    /**
     * Gets the soap template.
     * 
     * @return the soap template
     */
    public byte[] getSoapTemplate() {
        return this.soapTemplate;
    }

    /**
     * Sets the soap template.
     * 
     * @param soapTemplate
     *            the new soap template
     */
    public void setSoapTemplate(byte[] soapTemplate) {
        this.soapTemplate = soapTemplate;
    }

    /**
     * Gets the deploy date.
     * 
     * @return the deploy date
     */
    public Date getDeployDate() {
        return this.deployDate;
    }

    /**
     * Sets the deploy date.
     * 
     * @param deployDate
     *            the new deploy date
     */
    public void setDeployDate(Date deployDate) {
        this.deployDate = deployDate;
    }

    /**
     * Gets the version.
     * 
     * @return the version
     */
    public long getVersion() {
        return this.version;
    }

    /**
     * Sets the version.
     * 
     * @param version
     *            the new version
     */
    public void setVersion(long version) {
        this.version = version;
    }

    /**
     * Gets the workflow model is deployed on servers.
     * 
     * @return the workflow model is deployed on servers
     */
    public Set<WorkflowModelIsDeployedOnServer> getWorkflowModelIsDeployedOnServers() {
        return this.workflowModelIsDeployedOnServers;
    }

    /**
     * Sets the workflow model is deployed on servers.
     * 
     * @param workflowModelIsDeployedOnServers
     *            the new workflow model is deployed on servers
     */
    public void setWorkflowModelIsDeployedOnServers(
            Set<WorkflowModelIsDeployedOnServer> workflowModelIsDeployedOnServers) {
        this.workflowModelIsDeployedOnServers = workflowModelIsDeployedOnServers;
    }

    /**
     * Gets the start configurations.
     * 
     * @return the start configurations
     */
    public Set<StartConfiguration> getStartConfigurations() {
        return this.startConfigurations;
    }

    /**
     * Sets the start configurations.
     * 
     * @param startConfigurations
     *            the new start configurations
     */
    public void setStartConfigurations(
            Set<StartConfiguration> startConfigurations) {
        this.startConfigurations = startConfigurations;
    }

    /**
     * Gets the workflow instances.
     * 
     * @return the workflow instances
     */
    public Set<WorkflowInstance> getWorkflowInstances() {
        return this.workflowInstances;
    }

    /**
     * Sets the workflow instances.
     * 
     * @param workflowInstances
     *            the new workflow instances
     */
    public void setWorkflowInstances(Set<WorkflowInstance> workflowInstances) {
        this.workflowInstances = workflowInstances;
    }

}
