/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Invitation generated by hbm2java.
 */
public class Invitation implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private Long id;

    /** The administrate workflow model. */
    private WorkflowModel administrateWorkflowModel;

    /** The sender. */
    private User sender;

    /** The receiver. */
    private User receiver;

    /** The join tenant. */
    private Tenant joinTenant;

    /** The participate in workflow instance. */
    private WorkflowInstance participateInWorkflowInstance;

    /** The creation date. */
    private Date creationDate;

    /**
     * Instantiates a new invitation.
     */
    public Invitation() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new invitation.
     * 
     * @param sender
     *            the sender
     * @param receiver
     *            the receiver
     * @param creationDate
     *            the creation date
     */
    public Invitation(User sender, User receiver, Date creationDate) {
        // generated minimal constructor
        this.sender = sender;
        this.receiver = receiver;
        this.creationDate = creationDate;
    }

    /**
     * Instantiates a new invitation.
     * 
     * @param administrateWorkflowModel
     *            the administrate workflow model
     * @param sender
     *            the sender
     * @param receiver
     *            the receiver
     * @param joinTenant
     *            the join tenant
     * @param participateInWorkflowInstance
     *            the participate in workflow instance
     * @param creationDate
     *            the creation date
     */
    public Invitation(WorkflowModel administrateWorkflowModel, User sender,
            User receiver, Tenant joinTenant,
            WorkflowInstance participateInWorkflowInstance, Date creationDate) {
        // generated full constructor
        this.administrateWorkflowModel = administrateWorkflowModel;
        this.sender = sender;
        this.receiver = receiver;
        this.joinTenant = joinTenant;
        this.participateInWorkflowInstance = participateInWorkflowInstance;
        this.creationDate = creationDate;
    }

    /**
     * Gets the administrate workflow model.
     * 
     * @return the administrate workflow model
     */
    public WorkflowModel getAdministrateWorkflowModel() {
        return this.administrateWorkflowModel;
    }

    /**
     * Gets the creation date.
     * 
     * @return the creation date
     */
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Gets the join tenant.
     * 
     * @return the join tenant
     */
    public Tenant getJoinTenant() {
        return this.joinTenant;
    }

    /**
     * Gets the participate in workflow instance.
     * 
     * @return the participate in workflow instance
     */
    public WorkflowInstance getParticipateInWorkflowInstance() {
        return this.participateInWorkflowInstance;
    }

    /**
     * Gets the receiver.
     * 
     * @return the receiver
     */
    public User getReceiver() {
        return this.receiver;
    }

    /**
     * Gets the sender.
     * 
     * @return the sender
     */
    public User getSender() {
        return this.sender;
    }

    /**
     * Sets the administrate workflow model.
     * 
     * @param administrateWorkflowModel
     *            the new administrate workflow model
     */
    public void setAdministrateWorkflowModel(
            WorkflowModel administrateWorkflowModel) {
        this.administrateWorkflowModel = administrateWorkflowModel;
    }

    /**
     * Sets the creation date.
     * 
     * @param creationDate
     *            the new creation date
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Sets the join tenant.
     * 
     * @param joinTenant
     *            the new join tenant
     */
    public void setJoinTenant(Tenant joinTenant) {
        this.joinTenant = joinTenant;
    }

    /**
     * Sets the participate in workflow instance.
     * 
     * @param participateInWorkflowInstance
     *            the new participate in workflow instance
     */
    public void setParticipateInWorkflowInstance(
            WorkflowInstance participateInWorkflowInstance) {
        this.participateInWorkflowInstance = participateInWorkflowInstance;
    }

    /**
     * Sets the receiver.
     * 
     * @param receiver
     *            the new receiver
     */
    public void setReceiver(User receiver) {
        this.receiver = receiver;
    }

    /**
     * Sets the sender.
     * 
     * @param sender
     *            the new sender
     */
    public void setSender(User sender) {
        this.sender = sender;
    }

}
