/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Log generated by hbm2java.
 */
public class Log implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private Long id;
    
    /** The prio. */
    private String prio;
    
    /** The iprio. */
    private Long iprio;
    
    /** The category. */
    private String category;
    
    /** The msg. */
    private String msg;
    
    /** The layout msg. */
    private String layoutMsg;
    
    /** The throwable. */
    private String throwable;
    
    /** The ndc. */
    private String ndc;
    
    /** The mdc. */
    private String mdc;
    
    /** The mdc2. */
    private String mdc2;
    
    /** The info. */
    private String info;
    
    /** The addon. */
    private String addon;
    
    /** The log date. */
    private Date logDate;
    
    /** The created by. */
    private String createdBy;
    
    /** The thread. */
    private String thread;

    /**
     * Instantiates a new log.
     */
    public Log() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new log.
     * 
     * @param prio
     *            the prio
     */
    public Log(String prio) {
        // generated minimal constructor
        this.prio = prio;
    }

    /**
     * Instantiates a new log.
     * 
     * @param prio
     *            the prio
     * @param iprio
     *            the iprio
     * @param category
     *            the category
     * @param msg
     *            the msg
     * @param layoutMsg
     *            the layout msg
     * @param throwable
     *            the throwable
     * @param ndc
     *            the ndc
     * @param mdc
     *            the mdc
     * @param mdc2
     *            the mdc2
     * @param info
     *            the info
     * @param addon
     *            the addon
     * @param logDate
     *            the log date
     * @param createdBy
     *            the created by
     * @param thread
     *            the thread
     */
    public Log(String prio, Long iprio, String category, String msg,
            String layoutMsg, String throwable, String ndc, String mdc,
            String mdc2, String info, String addon, Date logDate,
            String createdBy, String thread) {
        // generated full constructor
        this.prio = prio;
        this.iprio = iprio;
        this.category = category;
        this.msg = msg;
        this.layoutMsg = layoutMsg;
        this.throwable = throwable;
        this.ndc = ndc;
        this.mdc = mdc;
        this.mdc2 = mdc2;
        this.info = info;
        this.addon = addon;
        this.logDate = logDate;
        this.createdBy = createdBy;
        this.thread = thread;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the prio.
     * 
     * @return the prio
     */
    public String getPrio() {
        return this.prio;
    }

    /**
     * Sets the prio.
     * 
     * @param prio
     *            the new prio
     */
    public void setPrio(String prio) {
        this.prio = prio;
    }

    /**
     * Gets the iprio.
     * 
     * @return the iprio
     */
    public Long getIprio() {
        return this.iprio;
    }

    /**
     * Sets the iprio.
     * 
     * @param iprio
     *            the new iprio
     */
    public void setIprio(Long iprio) {
        this.iprio = iprio;
    }

    /**
     * Gets the category.
     * 
     * @return the category
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Sets the category.
     * 
     * @param category
     *            the new category
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Gets the msg.
     * 
     * @return the msg
     */
    public String getMsg() {
        return this.msg;
    }

    /**
     * Sets the msg.
     * 
     * @param msg
     *            the new msg
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * Gets the layout msg.
     * 
     * @return the layout msg
     */
    public String getLayoutMsg() {
        return this.layoutMsg;
    }

    /**
     * Sets the layout msg.
     * 
     * @param layoutMsg
     *            the new layout msg
     */
    public void setLayoutMsg(String layoutMsg) {
        this.layoutMsg = layoutMsg;
    }

    /**
     * Gets the throwable.
     * 
     * @return the throwable
     */
    public String getThrowable() {
        return this.throwable;
    }

    /**
     * Sets the throwable.
     * 
     * @param throwable
     *            the new throwable
     */
    public void setThrowable(String throwable) {
        this.throwable = throwable;
    }

    /**
     * Gets the ndc.
     * 
     * @return the ndc
     */
    public String getNdc() {
        return this.ndc;
    }

    /**
     * Sets the ndc.
     * 
     * @param ndc
     *            the new ndc
     */
    public void setNdc(String ndc) {
        this.ndc = ndc;
    }

    /**
     * Gets the mdc.
     * 
     * @return the mdc
     */
    public String getMdc() {
        return this.mdc;
    }

    /**
     * Sets the mdc.
     * 
     * @param mdc
     *            the new mdc
     */
    public void setMdc(String mdc) {
        this.mdc = mdc;
    }

    /**
     * Gets the mdc2.
     * 
     * @return the mdc2
     */
    public String getMdc2() {
        return this.mdc2;
    }

    /**
     * Sets the mdc2.
     * 
     * @param mdc2
     *            the new mdc2
     */
    public void setMdc2(String mdc2) {
        this.mdc2 = mdc2;
    }

    /**
     * Gets the info.
     * 
     * @return the info
     */
    public String getInfo() {
        return this.info;
    }

    /**
     * Sets the info.
     * 
     * @param info
     *            the new info
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * Gets the addon.
     * 
     * @return the addon
     */
    public String getAddon() {
        return this.addon;
    }

    /**
     * Sets the addon.
     * 
     * @param addon
     *            the new addon
     */
    public void setAddon(String addon) {
        this.addon = addon;
    }

    /**
     * Gets the log date.
     * 
     * @return the log date
     */
    public Date getLogDate() {
        return this.logDate;
    }

    /**
     * Sets the log date.
     * 
     * @param logDate
     *            the new log date
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * Gets the created by.
     * 
     * @return the created by
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Sets the created by.
     * 
     * @param createdBy
     *            the new created by
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Gets the thread.
     * 
     * @return the thread
     */
    public String getThread() {
        return this.thread;
    }

    /**
     * Sets the thread.
     * 
     * @param thread
     *            the new thread
     */
    public void setThread(String thread) {
        this.thread = thread;
    }

}
