package de.decidr.model.entities;

// Generated 05.06.2009 17:08:24 by Hibernate Tools 3.2.2.GA

/**
 * RoleHasPermission generated by hbm2java
 */
public class RoleHasPermission implements java.io.Serializable {

    private RoleHasPermissionId id;
    private Permission resource;
    private Role role;

    public RoleHasPermission() {
    }

    public RoleHasPermission(RoleHasPermissionId id, Permission resource,
            Role role) {
        this.id = id;
        this.resource = resource;
        this.role = role;
    }

    public RoleHasPermissionId getId() {
        return this.id;
    }

    public void setId(RoleHasPermissionId id) {
        this.id = id;
    }

    public Permission getResource() {
        return this.resource;
    }

    public void setResource(Permission resource) {
        this.resource = resource;
    }

    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    // The following is extra code specified in the hbm.xml files
    private static final long serialVersionUID = 1L;
    // end of extra code specified in the hbm.xml files

}
