package de.decidr.model.entities;

// Generated 20.06.2009 16:18:37 by Hibernate Tools 3.2.4.GA

/**
 * SystemSettings generated by hbm2java
 */
public class SystemSettings implements java.io.Serializable {

    private Long id;
    private User superAdmin;
    private boolean autoAcceptNewTenants;
    private String logLevel;
    private int passwordResetRequestLifetimeSeconds;
    private int registrationRequestLifetimeSeconds;
    private int changeEmailRequestLifetimeSeconds;
    private int invitationLifetimeSeconds;

    public SystemSettings() {
    }

    public SystemSettings(boolean autoAcceptNewTenants, String logLevel,
            int passwordResetRequestLifetimeSeconds,
            int registrationRequestLifetimeSeconds,
            int changeEmailRequestLifetimeSeconds, int invitationLifetimeSeconds) {
        this.autoAcceptNewTenants = autoAcceptNewTenants;
        this.logLevel = logLevel;
        this.passwordResetRequestLifetimeSeconds = passwordResetRequestLifetimeSeconds;
        this.registrationRequestLifetimeSeconds = registrationRequestLifetimeSeconds;
        this.changeEmailRequestLifetimeSeconds = changeEmailRequestLifetimeSeconds;
        this.invitationLifetimeSeconds = invitationLifetimeSeconds;
    }

    public SystemSettings(User superAdmin, boolean autoAcceptNewTenants,
            String logLevel, int passwordResetRequestLifetimeSeconds,
            int registrationRequestLifetimeSeconds,
            int changeEmailRequestLifetimeSeconds, int invitationLifetimeSeconds) {
        this.superAdmin = superAdmin;
        this.autoAcceptNewTenants = autoAcceptNewTenants;
        this.logLevel = logLevel;
        this.passwordResetRequestLifetimeSeconds = passwordResetRequestLifetimeSeconds;
        this.registrationRequestLifetimeSeconds = registrationRequestLifetimeSeconds;
        this.changeEmailRequestLifetimeSeconds = changeEmailRequestLifetimeSeconds;
        this.invitationLifetimeSeconds = invitationLifetimeSeconds;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getSuperAdmin() {
        return this.superAdmin;
    }

    public void setSuperAdmin(User superAdmin) {
        this.superAdmin = superAdmin;
    }

    public boolean isAutoAcceptNewTenants() {
        return this.autoAcceptNewTenants;
    }

    public void setAutoAcceptNewTenants(boolean autoAcceptNewTenants) {
        this.autoAcceptNewTenants = autoAcceptNewTenants;
    }

    public String getLogLevel() {
        return this.logLevel;
    }

    public void setLogLevel(String logLevel) {
        this.logLevel = logLevel;
    }

    public int getPasswordResetRequestLifetimeSeconds() {
        return this.passwordResetRequestLifetimeSeconds;
    }

    public void setPasswordResetRequestLifetimeSeconds(
            int passwordResetRequestLifetimeSeconds) {
        this.passwordResetRequestLifetimeSeconds = passwordResetRequestLifetimeSeconds;
    }

    public int getRegistrationRequestLifetimeSeconds() {
        return this.registrationRequestLifetimeSeconds;
    }

    public void setRegistrationRequestLifetimeSeconds(
            int registrationRequestLifetimeSeconds) {
        this.registrationRequestLifetimeSeconds = registrationRequestLifetimeSeconds;
    }

    public int getChangeEmailRequestLifetimeSeconds() {
        return this.changeEmailRequestLifetimeSeconds;
    }

    public void setChangeEmailRequestLifetimeSeconds(
            int changeEmailRequestLifetimeSeconds) {
        this.changeEmailRequestLifetimeSeconds = changeEmailRequestLifetimeSeconds;
    }

    public int getInvitationLifetimeSeconds() {
        return this.invitationLifetimeSeconds;
    }

    public void setInvitationLifetimeSeconds(int invitationLifetimeSeconds) {
        this.invitationLifetimeSeconds = invitationLifetimeSeconds;
    }

}
