/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 28.12.2009 10:39:25 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * TenantSummaryView generated by hbm2java.
 */
public class TenantSummaryView implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private long id;

    /** The tenant name. */
    private String tenantName;

    /** The approved since. */
    private Date approvedSince;

    /** The admin first name. */
    private String adminFirstName;

    /** The admin last name. */
    private String adminLastName;

    /** The num workflow models. */
    private Long numWorkflowModels;

    /** The num deployed workflow models. */
    private Long numDeployedWorkflowModels;

    /** The num workflow instances. */
    private Long numWorkflowInstances;

    /** The num members. */
    private Long numMembers;

    /**
     * Instantiates a new tenant summary view.
     */
    public TenantSummaryView() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new tenant summary view.
     * 
     * @param id
     *            the id
     * @param tenantName
     *            the tenant name
     */
    public TenantSummaryView(long id, String tenantName) {
        // generated minimal constructor
        this.id = id;
        this.tenantName = tenantName;
    }

    /**
     * Instantiates a new tenant summary view.
     * 
     * @param id
     *            the id
     * @param tenantName
     *            the tenant name
     * @param approvedSince
     *            the approved since
     * @param adminFirstName
     *            the admin first name
     * @param adminLastName
     *            the admin last name
     * @param numWorkflowModels
     *            the num workflow models
     * @param numDeployedWorkflowModels
     *            the num deployed workflow models
     * @param numWorkflowInstances
     *            the num workflow instances
     * @param numMembers
     *            the num members
     */
    public TenantSummaryView(long id, String tenantName, Date approvedSince,
            String adminFirstName, String adminLastName,
            Long numWorkflowModels, Long numDeployedWorkflowModels,
            Long numWorkflowInstances, Long numMembers) {
        // generated full constructor
        this.id = id;
        this.tenantName = tenantName;
        this.approvedSince = approvedSince;
        this.adminFirstName = adminFirstName;
        this.adminLastName = adminLastName;
        this.numWorkflowModels = numWorkflowModels;
        this.numDeployedWorkflowModels = numDeployedWorkflowModels;
        this.numWorkflowInstances = numWorkflowInstances;
        this.numMembers = numMembers;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public long getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the tenant name.
     * 
     * @return the tenant name
     */
    public String getTenantName() {
        return this.tenantName;
    }

    /**
     * Sets the tenant name.
     * 
     * @param tenantName
     *            the new tenant name
     */
    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    /**
     * Gets the approved since.
     * 
     * @return the approved since
     */
    public Date getApprovedSince() {
        return this.approvedSince;
    }

    /**
     * Sets the approved since.
     * 
     * @param approvedSince
     *            the new approved since
     */
    public void setApprovedSince(Date approvedSince) {
        this.approvedSince = approvedSince;
    }

    /**
     * Gets the admin first name.
     * 
     * @return the admin first name
     */
    public String getAdminFirstName() {
        return this.adminFirstName;
    }

    /**
     * Sets the admin first name.
     * 
     * @param adminFirstName
     *            the new admin first name
     */
    public void setAdminFirstName(String adminFirstName) {
        this.adminFirstName = adminFirstName;
    }

    /**
     * Gets the admin last name.
     * 
     * @return the admin last name
     */
    public String getAdminLastName() {
        return this.adminLastName;
    }

    /**
     * Sets the admin last name.
     * 
     * @param adminLastName
     *            the new admin last name
     */
    public void setAdminLastName(String adminLastName) {
        this.adminLastName = adminLastName;
    }

    /**
     * Gets the num workflow models.
     * 
     * @return the num workflow models
     */
    public Long getNumWorkflowModels() {
        return this.numWorkflowModels;
    }

    /**
     * Sets the num workflow models.
     * 
     * @param numWorkflowModels
     *            the new num workflow models
     */
    public void setNumWorkflowModels(Long numWorkflowModels) {
        this.numWorkflowModels = numWorkflowModels;
    }

    /**
     * Gets the num deployed workflow models.
     * 
     * @return the num deployed workflow models
     */
    public Long getNumDeployedWorkflowModels() {
        return this.numDeployedWorkflowModels;
    }

    /**
     * Sets the num deployed workflow models.
     * 
     * @param numDeployedWorkflowModels
     *            the new num deployed workflow models
     */
    public void setNumDeployedWorkflowModels(Long numDeployedWorkflowModels) {
        this.numDeployedWorkflowModels = numDeployedWorkflowModels;
    }

    /**
     * Gets the num workflow instances.
     * 
     * @return the num workflow instances
     */
    public Long getNumWorkflowInstances() {
        return this.numWorkflowInstances;
    }

    /**
     * Sets the num workflow instances.
     * 
     * @param numWorkflowInstances
     *            the new num workflow instances
     */
    public void setNumWorkflowInstances(Long numWorkflowInstances) {
        this.numWorkflowInstances = numWorkflowInstances;
    }

    /**
     * Gets the num members.
     * 
     * @return the num members
     */
    public Long getNumMembers() {
        return this.numMembers;
    }

    /**
     * Sets the num members.
     * 
     * @param numMembers
     *            the new num members
     */
    public void setNumMembers(Long numMembers) {
        this.numMembers = numMembers;
    }

}
