package de.decidr.model.entities;

// Generated 07.05.2009 13:21:40 by Hibernate Tools 3.2.2.GA

/**
 * TenantSummaryView generated by hbm2java
 */
public class TenantSummaryView implements java.io.Serializable {

	private TenantSummaryViewId id;

	public TenantSummaryView() {
	}

	public TenantSummaryView(TenantSummaryViewId id) {
		this.id = id;
	}

	public TenantSummaryViewId getId() {
		return this.id;
	}

	public void setId(TenantSummaryViewId id) {
		this.id = id;
	}

}
