/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * TenantWithAdminView generated by hbm2java.
 */
public class TenantWithAdminView implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private long id;

    /** The name. */
    private String name;

    /** The description. */
    private String description;

    /** The logo id. */
    private Long logoId;

    /** The simple color scheme id. */
    private Long simpleColorSchemeId;

    /** The advanced color scheme id. */
    private Long advancedColorSchemeId;

    /** The current color scheme id. */
    private Long currentColorSchemeId;

    /** The approved since. */
    private Date approvedSince;

    /** The admin id. */
    private long adminId;

    /** The admin username. */
    private String adminUsername;

    /** The admin first name. */
    private String adminFirstName;

    /** The admin last name. */
    private String adminLastName;

    /**
     * Instantiates a new tenant with admin view.
     */
    public TenantWithAdminView() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new tenant with admin view.
     * 
     * @param id
     *            the id
     * @param name
     *            the name
     * @param description
     *            the description
     * @param adminId
     *            the admin id
     */
    public TenantWithAdminView(long id, String name, String description,
            long adminId) {
        // generated minimal constructor
        this.id = id;
        this.name = name;
        this.description = description;
        this.adminId = adminId;
    }

    /**
     * Instantiates a new tenant with admin view.
     * 
     * @param id
     *            the id
     * @param name
     *            the name
     * @param description
     *            the description
     * @param logoId
     *            the logo id
     * @param simpleColorSchemeId
     *            the simple color scheme id
     * @param advancedColorSchemeId
     *            the advanced color scheme id
     * @param currentColorSchemeId
     *            the current color scheme id
     * @param approvedSince
     *            the approved since
     * @param adminId
     *            the admin id
     * @param adminUsername
     *            the admin username
     * @param adminFirstName
     *            the admin first name
     * @param adminLastName
     *            the admin last name
     */
    public TenantWithAdminView(long id, String name, String description,
            Long logoId, Long simpleColorSchemeId, Long advancedColorSchemeId,
            Long currentColorSchemeId, Date approvedSince, long adminId,
            String adminUsername, String adminFirstName, String adminLastName) {
        // generated full constructor
        this.id = id;
        this.name = name;
        this.description = description;
        this.logoId = logoId;
        this.simpleColorSchemeId = simpleColorSchemeId;
        this.advancedColorSchemeId = advancedColorSchemeId;
        this.currentColorSchemeId = currentColorSchemeId;
        this.approvedSince = approvedSince;
        this.adminId = adminId;
        this.adminUsername = adminUsername;
        this.adminFirstName = adminFirstName;
        this.adminLastName = adminLastName;
    }

    /**
     * Gets the admin first name.
     * 
     * @return the admin first name
     */
    public String getAdminFirstName() {
        return this.adminFirstName;
    }

    /**
     * Gets the admin id.
     * 
     * @return the admin id
     */
    public long getAdminId() {
        return this.adminId;
    }

    /**
     * Gets the admin last name.
     * 
     * @return the admin last name
     */
    public String getAdminLastName() {
        return this.adminLastName;
    }

    /**
     * Gets the admin username.
     * 
     * @return the admin username
     */
    public String getAdminUsername() {
        return this.adminUsername;
    }

    /**
     * Gets the advanced color scheme id.
     * 
     * @return the advanced color scheme id
     */
    public Long getAdvancedColorSchemeId() {
        return this.advancedColorSchemeId;
    }

    /**
     * Gets the approved since.
     * 
     * @return the approved since
     */
    public Date getApprovedSince() {
        return this.approvedSince;
    }

    /**
     * Gets the current color scheme id.
     * 
     * @return the current color scheme id
     */
    public Long getCurrentColorSchemeId() {
        return this.currentColorSchemeId;
    }

    /**
     * Gets the description.
     * 
     * @return the description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public long getId() {
        return this.id;
    }

    /**
     * Gets the logo id.
     * 
     * @return the logo id
     */
    public Long getLogoId() {
        return this.logoId;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Gets the simple color scheme id.
     * 
     * @return the simple color scheme id
     */
    public Long getSimpleColorSchemeId() {
        return this.simpleColorSchemeId;
    }

    /**
     * Sets the admin first name.
     * 
     * @param adminFirstName
     *            the new admin first name
     */
    public void setAdminFirstName(String adminFirstName) {
        this.adminFirstName = adminFirstName;
    }

    /**
     * Sets the admin id.
     * 
     * @param adminId
     *            the new admin id
     */
    public void setAdminId(long adminId) {
        this.adminId = adminId;
    }

    /**
     * Sets the admin last name.
     * 
     * @param adminLastName
     *            the new admin last name
     */
    public void setAdminLastName(String adminLastName) {
        this.adminLastName = adminLastName;
    }

    /**
     * Sets the admin username.
     * 
     * @param adminUsername
     *            the new admin username
     */
    public void setAdminUsername(String adminUsername) {
        this.adminUsername = adminUsername;
    }

    /**
     * Sets the advanced color scheme id.
     * 
     * @param advancedColorSchemeId
     *            the new advanced color scheme id
     */
    public void setAdvancedColorSchemeId(Long advancedColorSchemeId) {
        this.advancedColorSchemeId = advancedColorSchemeId;
    }

    /**
     * Sets the approved since.
     * 
     * @param approvedSince
     *            the new approved since
     */
    public void setApprovedSince(Date approvedSince) {
        this.approvedSince = approvedSince;
    }

    /**
     * Sets the current color scheme id.
     * 
     * @param currentColorSchemeId
     *            the new current color scheme id
     */
    public void setCurrentColorSchemeId(Long currentColorSchemeId) {
        this.currentColorSchemeId = currentColorSchemeId;
    }

    /**
     * Sets the description.
     * 
     * @param description
     *            the new description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Sets the logo id.
     * 
     * @param logoId
     *            the new logo id
     */
    public void setLogoId(Long logoId) {
        this.logoId = logoId;
    }

    /**
     * Sets the name.
     * 
     * @param name
     *            the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Sets the simple color scheme id.
     * 
     * @param simpleColorSchemeId
     *            the new simple color scheme id
     */
    public void setSimpleColorSchemeId(Long simpleColorSchemeId) {
        this.simpleColorSchemeId = simpleColorSchemeId;
    }

}
