/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 28.12.2009 10:39:25 by Hibernate Tools 3.2.4.GA

/**
 * UserIsMemberOfTenantId generated by hbm2java.
 */
public class UserIsMemberOfTenantId implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The user id. */
    private long userId;

    /** The tenant id. */
    private long tenantId;

    /**
     * Instantiates a new user is member of tenant id.
     */
    public UserIsMemberOfTenantId() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new user is member of tenant id.
     * 
     * @param userId
     *            the user id
     * @param tenantId
     *            the tenant id
     */
    public UserIsMemberOfTenantId(long userId, long tenantId) {
        // generated full constructor
        this.userId = userId;
        this.tenantId = tenantId;
    }

    /**
     * Gets the user id.
     * 
     * @return the user id
     */
    public long getUserId() {
        return this.userId;
    }

    /**
     * Sets the user id.
     * 
     * @param userId
     *            the new user id
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * Gets the tenant id.
     * 
     * @return the tenant id
     */
    public long getTenantId() {
        return this.tenantId;
    }

    /**
     * Sets the tenant id.
     * 
     * @param tenantId
     *            the new tenant id
     */
    public void setTenantId(long tenantId) {
        this.tenantId = tenantId;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserIsMemberOfTenantId))
            return false;
        UserIsMemberOfTenantId castOther = (UserIsMemberOfTenantId) other;

        return (this.getUserId() == castOther.getUserId())
                && (this.getTenantId() == castOther.getTenantId());
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getUserId();
        result = 37 * result + (int) this.getTenantId();
        return result;
    }

}
