/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 28.12.2009 10:39:25 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java.
 */
public class User implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private Long id;

    /** The current tenant. */
    private Tenant currentTenant;

    /** The auth key. */
    private String authKey;

    /** The email. */
    private String email;

    /** The disabled since. */
    private Date disabledSince;

    /** The unavailable since. */
    private Date unavailableSince;

    /** The registered since. */
    private Date registeredSince;

    /** The creation date. */
    private Date creationDate;

    /** The work items. */
    private Set<WorkItem> workItems = new HashSet<WorkItem>(0);

    /** The invitations for sender id. */
    private Set<Invitation> invitationsForSenderId = new HashSet<Invitation>(0);

    /** The workflow models. */
    private Set<WorkflowModel> workflowModels = new HashSet<WorkflowModel>(0);

    /** The user is member of tenants. */
    private Set<UserIsMemberOfTenant> userIsMemberOfTenants = new HashSet<UserIsMemberOfTenant>(
            0);

    /** The user profile. */
    private UserProfile userProfile;

    /** The password reset request. */
    private PasswordResetRequest passwordResetRequest;

    /** The registration request. */
    private RegistrationRequest registrationRequest;

    /** The invitations for receiver id. */
    private Set<Invitation> invitationsForReceiverId = new HashSet<Invitation>(
            0);

    /** The user administrates workflow instances. */
    private Set<UserAdministratesWorkflowInstance> userAdministratesWorkflowInstances = new HashSet<UserAdministratesWorkflowInstance>(
            0);

    /** The system settings. */
    private Set<SystemSettings> systemSettings = new HashSet<SystemSettings>(0);

    /** The user has file access. */
    private Set<UserHasFileAccess> userHasFileAccess = new HashSet<UserHasFileAccess>(
            0);

    /** The user participates in workflows. */
    private Set<UserParticipatesInWorkflow> userParticipatesInWorkflows = new HashSet<UserParticipatesInWorkflow>(
            0);

    /** The administrated tenants. */
    private Set<Tenant> administratedTenants = new HashSet<Tenant>(0);

    /** The logins. */
    private Set<Login> logins = new HashSet<Login>(0);

    /** The change email request. */
    private ChangeEmailRequest changeEmailRequest;

    /** The user administrates workflow models. */
    private Set<UserAdministratesWorkflowModel> userAdministratesWorkflowModels = new HashSet<UserAdministratesWorkflowModel>(
            0);

    /**
     * Instantiates a new user.
     */
    public User() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new user.
     * 
     * @param email
     *            the email
     * @param creationDate
     *            the creation date
     */
    public User(String email, Date creationDate) {
        // generated minimal constructor
        this.email = email;
        this.creationDate = creationDate;
    }

    /**
     * Instantiates a new user.
     * 
     * @param currentTenant
     *            the current tenant
     * @param authKey
     *            the auth key
     * @param email
     *            the email
     * @param disabledSince
     *            the disabled since
     * @param unavailableSince
     *            the unavailable since
     * @param registeredSince
     *            the registered since
     * @param creationDate
     *            the creation date
     * @param workItems
     *            the work items
     * @param invitationsForSenderId
     *            the invitations for sender id
     * @param workflowModels
     *            the workflow models
     * @param userIsMemberOfTenants
     *            the user is member of tenants
     * @param userProfile
     *            the user profile
     * @param passwordResetRequest
     *            the password reset request
     * @param registrationRequest
     *            the registration request
     * @param invitationsForReceiverId
     *            the invitations for receiver id
     * @param userAdministratesWorkflowInstances
     *            the user administrates workflow instances
     * @param systemSettings
     *            the system settings
     * @param userHasFileAccess
     *            the user has file access
     * @param userParticipatesInWorkflows
     *            the user participates in workflows
     * @param administratedTenants
     *            the administrated tenants
     * @param logins
     *            the logins
     * @param changeEmailRequest
     *            the change email request
     * @param userAdministratesWorkflowModels
     *            the user administrates workflow models
     */
    public User(
            Tenant currentTenant,
            String authKey,
            String email,
            Date disabledSince,
            Date unavailableSince,
            Date registeredSince,
            Date creationDate,
            Set<WorkItem> workItems,
            Set<Invitation> invitationsForSenderId,
            Set<WorkflowModel> workflowModels,
            Set<UserIsMemberOfTenant> userIsMemberOfTenants,
            UserProfile userProfile,
            PasswordResetRequest passwordResetRequest,
            RegistrationRequest registrationRequest,
            Set<Invitation> invitationsForReceiverId,
            Set<UserAdministratesWorkflowInstance> userAdministratesWorkflowInstances,
            Set<SystemSettings> systemSettings,
            Set<UserHasFileAccess> userHasFileAccess,
            Set<UserParticipatesInWorkflow> userParticipatesInWorkflows,
            Set<Tenant> administratedTenants, Set<Login> logins,
            ChangeEmailRequest changeEmailRequest,
            Set<UserAdministratesWorkflowModel> userAdministratesWorkflowModels) {
        // generated full constructor
        this.currentTenant = currentTenant;
        this.authKey = authKey;
        this.email = email;
        this.disabledSince = disabledSince;
        this.unavailableSince = unavailableSince;
        this.registeredSince = registeredSince;
        this.creationDate = creationDate;
        this.workItems = workItems;
        this.invitationsForSenderId = invitationsForSenderId;
        this.workflowModels = workflowModels;
        this.userIsMemberOfTenants = userIsMemberOfTenants;
        this.userProfile = userProfile;
        this.passwordResetRequest = passwordResetRequest;
        this.registrationRequest = registrationRequest;
        this.invitationsForReceiverId = invitationsForReceiverId;
        this.userAdministratesWorkflowInstances = userAdministratesWorkflowInstances;
        this.systemSettings = systemSettings;
        this.userHasFileAccess = userHasFileAccess;
        this.userParticipatesInWorkflows = userParticipatesInWorkflows;
        this.administratedTenants = administratedTenants;
        this.logins = logins;
        this.changeEmailRequest = changeEmailRequest;
        this.userAdministratesWorkflowModels = userAdministratesWorkflowModels;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the current tenant.
     * 
     * @return the current tenant
     */
    public Tenant getCurrentTenant() {
        return this.currentTenant;
    }

    /**
     * Sets the current tenant.
     * 
     * @param currentTenant
     *            the new current tenant
     */
    public void setCurrentTenant(Tenant currentTenant) {
        this.currentTenant = currentTenant;
    }

    /**
     * Gets the auth key.
     * 
     * @return the auth key
     */
    public String getAuthKey() {
        return this.authKey;
    }

    /**
     * Sets the auth key.
     * 
     * @param authKey
     *            the new auth key
     */
    public void setAuthKey(String authKey) {
        this.authKey = authKey;
    }

    /**
     * Gets the email.
     * 
     * @return the email
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Sets the email.
     * 
     * @param email
     *            the new email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the disabled since.
     * 
     * @return the disabled since
     */
    public Date getDisabledSince() {
        return this.disabledSince;
    }

    /**
     * Sets the disabled since.
     * 
     * @param disabledSince
     *            the new disabled since
     */
    public void setDisabledSince(Date disabledSince) {
        this.disabledSince = disabledSince;
    }

    /**
     * Gets the unavailable since.
     * 
     * @return the unavailable since
     */
    public Date getUnavailableSince() {
        return this.unavailableSince;
    }

    /**
     * Sets the unavailable since.
     * 
     * @param unavailableSince
     *            the new unavailable since
     */
    public void setUnavailableSince(Date unavailableSince) {
        this.unavailableSince = unavailableSince;
    }

    /**
     * Gets the registered since.
     * 
     * @return the registered since
     */
    public Date getRegisteredSince() {
        return this.registeredSince;
    }

    /**
     * Sets the registered since.
     * 
     * @param registeredSince
     *            the new registered since
     */
    public void setRegisteredSince(Date registeredSince) {
        this.registeredSince = registeredSince;
    }

    /**
     * Gets the creation date.
     * 
     * @return the creation date
     */
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     * Sets the creation date.
     * 
     * @param creationDate
     *            the new creation date
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * Gets the work items.
     * 
     * @return the work items
     */
    public Set<WorkItem> getWorkItems() {
        return this.workItems;
    }

    /**
     * Sets the work items.
     * 
     * @param workItems
     *            the new work items
     */
    public void setWorkItems(Set<WorkItem> workItems) {
        this.workItems = workItems;
    }

    /**
     * Gets the invitations for sender id.
     * 
     * @return the invitations for sender id
     */
    public Set<Invitation> getInvitationsForSenderId() {
        return this.invitationsForSenderId;
    }

    /**
     * Sets the invitations for sender id.
     * 
     * @param invitationsForSenderId
     *            the new invitations for sender id
     */
    public void setInvitationsForSenderId(Set<Invitation> invitationsForSenderId) {
        this.invitationsForSenderId = invitationsForSenderId;
    }

    /**
     * Gets the workflow models.
     * 
     * @return the workflow models
     */
    public Set<WorkflowModel> getWorkflowModels() {
        return this.workflowModels;
    }

    /**
     * Sets the workflow models.
     * 
     * @param workflowModels
     *            the new workflow models
     */
    public void setWorkflowModels(Set<WorkflowModel> workflowModels) {
        this.workflowModels = workflowModels;
    }

    /**
     * Gets the user is member of tenants.
     * 
     * @return the user is member of tenants
     */
    public Set<UserIsMemberOfTenant> getUserIsMemberOfTenants() {
        return this.userIsMemberOfTenants;
    }

    /**
     * Sets the user is member of tenants.
     * 
     * @param userIsMemberOfTenants
     *            the new user is member of tenants
     */
    public void setUserIsMemberOfTenants(
            Set<UserIsMemberOfTenant> userIsMemberOfTenants) {
        this.userIsMemberOfTenants = userIsMemberOfTenants;
    }

    /**
     * Gets the user profile.
     * 
     * @return the user profile
     */
    public UserProfile getUserProfile() {
        return this.userProfile;
    }

    /**
     * Sets the user profile.
     * 
     * @param userProfile
     *            the new user profile
     */
    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }

    /**
     * Gets the password reset request.
     * 
     * @return the password reset request
     */
    public PasswordResetRequest getPasswordResetRequest() {
        return this.passwordResetRequest;
    }

    /**
     * Sets the password reset request.
     * 
     * @param passwordResetRequest
     *            the new password reset request
     */
    public void setPasswordResetRequest(
            PasswordResetRequest passwordResetRequest) {
        this.passwordResetRequest = passwordResetRequest;
    }

    /**
     * Gets the registration request.
     * 
     * @return the registration request
     */
    public RegistrationRequest getRegistrationRequest() {
        return this.registrationRequest;
    }

    /**
     * Sets the registration request.
     * 
     * @param registrationRequest
     *            the new registration request
     */
    public void setRegistrationRequest(RegistrationRequest registrationRequest) {
        this.registrationRequest = registrationRequest;
    }

    /**
     * Gets the invitations for receiver id.
     * 
     * @return the invitations for receiver id
     */
    public Set<Invitation> getInvitationsForReceiverId() {
        return this.invitationsForReceiverId;
    }

    /**
     * Sets the invitations for receiver id.
     * 
     * @param invitationsForReceiverId
     *            the new invitations for receiver id
     */
    public void setInvitationsForReceiverId(
            Set<Invitation> invitationsForReceiverId) {
        this.invitationsForReceiverId = invitationsForReceiverId;
    }

    /**
     * Gets the user administrates workflow instances.
     * 
     * @return the user administrates workflow instances
     */
    public Set<UserAdministratesWorkflowInstance> getUserAdministratesWorkflowInstances() {
        return this.userAdministratesWorkflowInstances;
    }

    /**
     * Sets the user administrates workflow instances.
     * 
     * @param userAdministratesWorkflowInstances
     *            the new user administrates workflow instances
     */
    public void setUserAdministratesWorkflowInstances(
            Set<UserAdministratesWorkflowInstance> userAdministratesWorkflowInstances) {
        this.userAdministratesWorkflowInstances = userAdministratesWorkflowInstances;
    }

    /**
     * Gets the system settings.
     * 
     * @return the system settings
     */
    public Set<SystemSettings> getSystemSettings() {
        return this.systemSettings;
    }

    /**
     * Sets the system settings.
     * 
     * @param systemSettings
     *            the new system settings
     */
    public void setSystemSettings(Set<SystemSettings> systemSettings) {
        this.systemSettings = systemSettings;
    }

    /**
     * Gets the user has file access.
     * 
     * @return the user has file access
     */
    public Set<UserHasFileAccess> getUserHasFileAccess() {
        return this.userHasFileAccess;
    }

    /**
     * Sets the user has file access.
     * 
     * @param userHasFileAccess
     *            the new user has file access
     */
    public void setUserHasFileAccess(Set<UserHasFileAccess> userHasFileAccess) {
        this.userHasFileAccess = userHasFileAccess;
    }

    /**
     * Gets the user participates in workflows.
     * 
     * @return the user participates in workflows
     */
    public Set<UserParticipatesInWorkflow> getUserParticipatesInWorkflows() {
        return this.userParticipatesInWorkflows;
    }

    /**
     * Sets the user participates in workflows.
     * 
     * @param userParticipatesInWorkflows
     *            the new user participates in workflows
     */
    public void setUserParticipatesInWorkflows(
            Set<UserParticipatesInWorkflow> userParticipatesInWorkflows) {
        this.userParticipatesInWorkflows = userParticipatesInWorkflows;
    }

    /**
     * Gets the administrated tenants.
     * 
     * @return the administrated tenants
     */
    public Set<Tenant> getAdministratedTenants() {
        return this.administratedTenants;
    }

    /**
     * Sets the administrated tenants.
     * 
     * @param administratedTenants
     *            the new administrated tenants
     */
    public void setAdministratedTenants(Set<Tenant> administratedTenants) {
        this.administratedTenants = administratedTenants;
    }

    /**
     * Gets the logins.
     * 
     * @return the logins
     */
    public Set<Login> getLogins() {
        return this.logins;
    }

    /**
     * Sets the logins.
     * 
     * @param logins
     *            the new logins
     */
    public void setLogins(Set<Login> logins) {
        this.logins = logins;
    }

    /**
     * Gets the change email request.
     * 
     * @return the change email request
     */
    public ChangeEmailRequest getChangeEmailRequest() {
        return this.changeEmailRequest;
    }

    /**
     * Sets the change email request.
     * 
     * @param changeEmailRequest
     *            the new change email request
     */
    public void setChangeEmailRequest(ChangeEmailRequest changeEmailRequest) {
        this.changeEmailRequest = changeEmailRequest;
    }

    /**
     * Gets the user administrates workflow models.
     * 
     * @return the user administrates workflow models
     */
    public Set<UserAdministratesWorkflowModel> getUserAdministratesWorkflowModels() {
        return this.userAdministratesWorkflowModels;
    }

    /**
     * Sets the user administrates workflow models.
     * 
     * @param userAdministratesWorkflowModels
     *            the new user administrates workflow models
     */
    public void setUserAdministratesWorkflowModels(
            Set<UserAdministratesWorkflowModel> userAdministratesWorkflowModels) {
        this.userAdministratesWorkflowModels = userAdministratesWorkflowModels;
    }

}
