package de.decidr.model.entities;

// Generated 07.12.2009 17:47:57 by Hibernate Tools 3.2.4.GA

/**
 * UserHasFileAccessId generated by hbm2java
 */
public class UserHasFileAccessId implements java.io.Serializable {

    private long userId;
    private long fileId;

    public UserHasFileAccessId() {
        //default empty JavaBean constructor
    }

    public UserHasFileAccessId(long userId, long fileId) {
        //generated full constructor
        this.userId = userId;
        this.fileId = fileId;
    }

    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getFileId() {
        return this.fileId;
    }

    public void setFileId(long fileId) {
        this.fileId = fileId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserHasFileAccessId))
            return false;
        UserHasFileAccessId castOther = (UserHasFileAccessId) other;

        return (this.getUserId() == castOther.getUserId())
                && (this.getFileId() == castOther.getFileId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getUserId();
        result = 37 * result + (int) this.getFileId();
        return result;
    }

}
