/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 28.12.2009 10:39:25 by Hibernate Tools 3.2.4.GA

/**
 * UserAdministratesWorkflowModel generated by hbm2java.
 */
public class UserAdministratesWorkflowModel implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private UserAdministratesWorkflowModelId id;

    /** The workflow model. */
    private WorkflowModel workflowModel;

    /** The user. */
    private User user;

    /**
     * Instantiates a new user administrates workflow model.
     */
    public UserAdministratesWorkflowModel() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new user administrates workflow model.
     * 
     * @param id
     *            the id
     * @param workflowModel
     *            the workflow model
     * @param user
     *            the user
     */
    public UserAdministratesWorkflowModel(UserAdministratesWorkflowModelId id,
            WorkflowModel workflowModel, User user) {
        // generated full constructor
        this.id = id;
        this.workflowModel = workflowModel;
        this.user = user;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public UserAdministratesWorkflowModelId getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(UserAdministratesWorkflowModelId id) {
        this.id = id;
    }

    /**
     * Gets the workflow model.
     * 
     * @return the workflow model
     */
    public WorkflowModel getWorkflowModel() {
        return this.workflowModel;
    }

    /**
     * Sets the workflow model.
     * 
     * @param workflowModel
     *            the new workflow model
     */
    public void setWorkflowModel(WorkflowModel workflowModel) {
        this.workflowModel = workflowModel;
    }

    /**
     * Gets the user.
     * 
     * @return the user
     */
    public User getUser() {
        return this.user;
    }

    /**
     * Sets the user.
     * 
     * @param user
     *            the new user
     */
    public void setUser(User user) {
        this.user = user;
    }

}
