/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

/**
 * UserAdministratesWorkflowInstance generated by hbm2java.
 */
public class UserAdministratesWorkflowInstance implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private UserAdministratesWorkflowInstanceId id;

    /** The workflow instance. */
    private WorkflowInstance workflowInstance;

    /** The user. */
    private User user;

    /**
     * Instantiates a new user administrates workflow instance.
     */
    public UserAdministratesWorkflowInstance() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new user administrates workflow instance.
     * 
     * @param id
     *            the id
     * @param workflowInstance
     *            the workflow instance
     * @param user
     *            the user
     */
    public UserAdministratesWorkflowInstance(
            UserAdministratesWorkflowInstanceId id,
            WorkflowInstance workflowInstance, User user) {
        // generated full constructor
        this.id = id;
        this.workflowInstance = workflowInstance;
        this.user = user;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public UserAdministratesWorkflowInstanceId getId() {
        return this.id;
    }

    /**
     * Gets the user.
     * 
     * @return the user
     */
    public User getUser() {
        return this.user;
    }

    /**
     * Gets the workflow instance.
     * 
     * @return the workflow instance
     */
    public WorkflowInstance getWorkflowInstance() {
        return this.workflowInstance;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(UserAdministratesWorkflowInstanceId id) {
        this.id = id;
    }

    /**
     * Sets the user.
     * 
     * @param user
     *            the new user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Sets the workflow instance.
     * 
     * @param workflowInstance
     *            the new workflow instance
     */
    public void setWorkflowInstance(WorkflowInstance workflowInstance) {
        this.workflowInstance = workflowInstance;
    }

}
