/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

/**
 * UserProfile generated by hbm2java.
 */
public class UserProfile implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private long id;
    
    /** The user. */
    private User user;
    
    /** The username. */
    private String username;
    
    /** The password hash. */
    private String passwordHash;
    
    /** The password salt. */
    private String passwordSalt;
    
    /** The first name. */
    private String firstName;
    
    /** The last name. */
    private String lastName;
    
    /** The street. */
    private String street;
    
    /** The postal code. */
    private String postalCode;
    
    /** The city. */
    private String city;

    /**
     * Instantiates a new user profile.
     */
    public UserProfile() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new user profile.
     * 
     * @param user
     *            the user
     * @param username
     *            the username
     * @param passwordHash
     *            the password hash
     * @param passwordSalt
     *            the password salt
     */
    public UserProfile(User user, String username, String passwordHash,
            String passwordSalt) {
        // generated minimal constructor
        this.user = user;
        this.username = username;
        this.passwordHash = passwordHash;
        this.passwordSalt = passwordSalt;
    }

    /**
     * Instantiates a new user profile.
     * 
     * @param user
     *            the user
     * @param username
     *            the username
     * @param passwordHash
     *            the password hash
     * @param passwordSalt
     *            the password salt
     * @param firstName
     *            the first name
     * @param lastName
     *            the last name
     * @param street
     *            the street
     * @param postalCode
     *            the postal code
     * @param city
     *            the city
     */
    public UserProfile(User user, String username, String passwordHash,
            String passwordSalt, String firstName, String lastName,
            String street, String postalCode, String city) {
        // generated full constructor
        this.user = user;
        this.username = username;
        this.passwordHash = passwordHash;
        this.passwordSalt = passwordSalt;
        this.firstName = firstName;
        this.lastName = lastName;
        this.street = street;
        this.postalCode = postalCode;
        this.city = city;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public long getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the user.
     * 
     * @return the user
     */
    public User getUser() {
        return this.user;
    }

    /**
     * Sets the user.
     * 
     * @param user
     *            the new user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Gets the username.
     * 
     * @return the username
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Sets the username.
     * 
     * @param username
     *            the new username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets the password hash.
     * 
     * @return the password hash
     */
    public String getPasswordHash() {
        return this.passwordHash;
    }

    /**
     * Sets the password hash.
     * 
     * @param passwordHash
     *            the new password hash
     */
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    /**
     * Gets the password salt.
     * 
     * @return the password salt
     */
    public String getPasswordSalt() {
        return this.passwordSalt;
    }

    /**
     * Sets the password salt.
     * 
     * @param passwordSalt
     *            the new password salt
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt;
    }

    /**
     * Gets the first name.
     * 
     * @return the first name
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Sets the first name.
     * 
     * @param firstName
     *            the new first name
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Gets the last name.
     * 
     * @return the last name
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Sets the last name.
     * 
     * @param lastName
     *            the new last name
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Gets the street.
     * 
     * @return the street
     */
    public String getStreet() {
        return this.street;
    }

    /**
     * Sets the street.
     * 
     * @param street
     *            the new street
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * Gets the postal code.
     * 
     * @return the postal code
     */
    public String getPostalCode() {
        return this.postalCode;
    }

    /**
     * Sets the postal code.
     * 
     * @param postalCode
     *            the new postal code
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * Gets the city.
     * 
     * @return the city
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Sets the city.
     * 
     * @param city
     *            the new city
     */
    public void setCity(String city) {
        this.city = city;
    }

}
