/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

/**
 * UserAdministratesWorkflowModelId generated by hbm2java.
 */
public class UserAdministratesWorkflowModelId implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The user id. */
    private long userId;

    /** The workflow model id. */
    private long workflowModelId;

    /**
     * Instantiates a new user administrates workflow model id.
     */
    public UserAdministratesWorkflowModelId() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new user administrates workflow model id.
     * 
     * @param userId
     *            the user id
     * @param workflowModelId
     *            the workflow model id
     */
    public UserAdministratesWorkflowModelId(long userId, long workflowModelId) {
        // generated full constructor
        this.userId = userId;
        this.workflowModelId = workflowModelId;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof UserAdministratesWorkflowModelId)) {
            return false;
        }
        UserAdministratesWorkflowModelId castOther = (UserAdministratesWorkflowModelId) other;

        return (this.getUserId() == castOther.getUserId())
                && (this.getWorkflowModelId() == castOther.getWorkflowModelId());
    }

    /**
     * Gets the user id.
     * 
     * @return the user id
     */
    public long getUserId() {
        return this.userId;
    }

    /**
     * Gets the workflow model id.
     * 
     * @return the workflow model id
     */
    public long getWorkflowModelId() {
        return this.workflowModelId;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getUserId();
        result = 37 * result + (int) this.getWorkflowModelId();
        return result;
    }

    /**
     * Sets the user id.
     * 
     * @param userId
     *            the new user id
     */
    public void setUserId(long userId) {
        this.userId = userId;
    }

    /**
     * Sets the workflow model id.
     * 
     * @param workflowModelId
     *            the new workflow model id
     */
    public void setWorkflowModelId(long workflowModelId) {
        this.workflowModelId = workflowModelId;
    }

}
