/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkflowModel generated by hbm2java.
 */
public class WorkflowModel implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private Long id;
    
    /** The tenant. */
    private Tenant tenant;
    
    /** The modified by user. */
    private User modifiedByUser;
    
    /** The name. */
    private String name;
    
    /** The description. */
    private String description;
    
    /** The published. */
    private boolean published;
    
    /** The executable. */
    private boolean executable;
    
    /** The creation date. */
    private Date creationDate;
    
    /** The modified date. */
    private Date modifiedDate;
    
    /** The dwdl. */
    private byte[] dwdl;
    
    /** The version. */
    private long version;
    
    /** The invitations. */
    private Set<Invitation> invitations = new HashSet<Invitation>(0);
    
    /** The user administrates workflow models. */
    private Set<UserAdministratesWorkflowModel> userAdministratesWorkflowModels = new HashSet<UserAdministratesWorkflowModel>(
            0);
    
    /** The deployed workflow models. */
    private Set<DeployedWorkflowModel> deployedWorkflowModels = new HashSet<DeployedWorkflowModel>(
            0);

    /**
     * Instantiates a new workflow model.
     */
    public WorkflowModel() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new workflow model.
     * 
     * @param tenant
     *            the tenant
     * @param name
     *            the name
     * @param description
     *            the description
     * @param published
     *            the published
     * @param executable
     *            the executable
     * @param creationDate
     *            the creation date
     * @param modifiedDate
     *            the modified date
     * @param dwdl
     *            the dwdl
     * @param version
     *            the version
     */
    public WorkflowModel(Tenant tenant, String name, String description,
            boolean published, boolean executable, Date creationDate,
            Date modifiedDate, byte[] dwdl, long version) {
        // generated minimal constructor
        this.tenant = tenant;
        this.name = name;
        this.description = description;
        this.published = published;
        this.executable = executable;
        this.creationDate = creationDate;
        this.modifiedDate = modifiedDate;
        this.dwdl = dwdl;
        this.version = version;
    }

    /**
     * Instantiates a new workflow model.
     * 
     * @param tenant
     *            the tenant
     * @param modifiedByUser
     *            the modified by user
     * @param name
     *            the name
     * @param description
     *            the description
     * @param published
     *            the published
     * @param executable
     *            the executable
     * @param creationDate
     *            the creation date
     * @param modifiedDate
     *            the modified date
     * @param dwdl
     *            the dwdl
     * @param version
     *            the version
     * @param invitations
     *            the invitations
     * @param userAdministratesWorkflowModels
     *            the user administrates workflow models
     * @param deployedWorkflowModels
     *            the deployed workflow models
     */
    public WorkflowModel(
            Tenant tenant,
            User modifiedByUser,
            String name,
            String description,
            boolean published,
            boolean executable,
            Date creationDate,
            Date modifiedDate,
            byte[] dwdl,
            long version,
            Set<Invitation> invitations,
            Set<UserAdministratesWorkflowModel> userAdministratesWorkflowModels,
            Set<DeployedWorkflowModel> deployedWorkflowModels) {
        // generated full constructor
        this.tenant = tenant;
        this.modifiedByUser = modifiedByUser;
        this.name = name;
        this.description = description;
        this.published = published;
        this.executable = executable;
        this.creationDate = creationDate;
        this.modifiedDate = modifiedDate;
        this.dwdl = dwdl;
        this.version = version;
        this.invitations = invitations;
        this.userAdministratesWorkflowModels = userAdministratesWorkflowModels;
        this.deployedWorkflowModels = deployedWorkflowModels;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the tenant.
     * 
     * @return the tenant
     */
    public Tenant getTenant() {
        return this.tenant;
    }

    /**
     * Sets the tenant.
     * 
     * @param tenant
     *            the new tenant
     */
    public void setTenant(Tenant tenant) {
        this.tenant = tenant;
    }

    /**
     * Gets the modified by user.
     * 
     * @return the modified by user
     */
    public User getModifiedByUser() {
        return this.modifiedByUser;
    }

    /**
     * Sets the modified by user.
     * 
     * @param modifiedByUser
     *            the new modified by user
     */
    public void setModifiedByUser(User modifiedByUser) {
        this.modifiedByUser = modifiedByUser;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the name.
     * 
     * @param name
     *            the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the description.
     * 
     * @return the description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the description.
     * 
     * @param description
     *            the new description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Checks if is published.
     * 
     * @return true, if is published
     */
    public boolean isPublished() {
        return this.published;
    }

    /**
     * Sets the published.
     * 
     * @param published
     *            the new published
     */
    public void setPublished(boolean published) {
        this.published = published;
    }

    /**
     * Checks if is executable.
     * 
     * @return true, if is executable
     */
    public boolean isExecutable() {
        return this.executable;
    }

    /**
     * Sets the executable.
     * 
     * @param executable
     *            the new executable
     */
    public void setExecutable(boolean executable) {
        this.executable = executable;
    }

    /**
     * Gets the creation date.
     * 
     * @return the creation date
     */
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     * Sets the creation date.
     * 
     * @param creationDate
     *            the new creation date
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * Gets the modified date.
     * 
     * @return the modified date
     */
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Sets the modified date.
     * 
     * @param modifiedDate
     *            the new modified date
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Gets the dwdl.
     * 
     * @return the dwdl
     */
    public byte[] getDwdl() {
        return this.dwdl;
    }

    /**
     * Sets the dwdl.
     * 
     * @param dwdl
     *            the new dwdl
     */
    public void setDwdl(byte[] dwdl) {
        this.dwdl = dwdl;
    }

    /**
     * Gets the version.
     * 
     * @return the version
     */
    public long getVersion() {
        return this.version;
    }

    /**
     * Sets the version.
     * 
     * @param version
     *            the new version
     */
    public void setVersion(long version) {
        this.version = version;
    }

    /**
     * Gets the invitations.
     * 
     * @return the invitations
     */
    public Set<Invitation> getInvitations() {
        return this.invitations;
    }

    /**
     * Sets the invitations.
     * 
     * @param invitations
     *            the new invitations
     */
    public void setInvitations(Set<Invitation> invitations) {
        this.invitations = invitations;
    }

    /**
     * Gets the user administrates workflow models.
     * 
     * @return the user administrates workflow models
     */
    public Set<UserAdministratesWorkflowModel> getUserAdministratesWorkflowModels() {
        return this.userAdministratesWorkflowModels;
    }

    /**
     * Sets the user administrates workflow models.
     * 
     * @param userAdministratesWorkflowModels
     *            the new user administrates workflow models
     */
    public void setUserAdministratesWorkflowModels(
            Set<UserAdministratesWorkflowModel> userAdministratesWorkflowModels) {
        this.userAdministratesWorkflowModels = userAdministratesWorkflowModels;
    }

    /**
     * Gets the deployed workflow models.
     * 
     * @return the deployed workflow models
     */
    public Set<DeployedWorkflowModel> getDeployedWorkflowModels() {
        return this.deployedWorkflowModels;
    }

    /**
     * Sets the deployed workflow models.
     * 
     * @param deployedWorkflowModels
     *            the new deployed workflow models
     */
    public void setDeployedWorkflowModels(
            Set<DeployedWorkflowModel> deployedWorkflowModels) {
        this.deployedWorkflowModels = deployedWorkflowModels;
    }

}
