/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

/**
 * WorkflowModelIsDeployedOnServerId generated by hbm2java.
 */
public class WorkflowModelIsDeployedOnServerId implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The deployed workflow model id. */
    private long deployedWorkflowModelId;

    /** The server id. */
    private long serverId;

    /**
     * Instantiates a new workflow model is deployed on server id.
     */
    public WorkflowModelIsDeployedOnServerId() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new workflow model is deployed on server id.
     * 
     * @param deployedWorkflowModelId
     *            the deployed workflow model id
     * @param serverId
     *            the server id
     */
    public WorkflowModelIsDeployedOnServerId(long deployedWorkflowModelId,
            long serverId) {
        // generated full constructor
        this.deployedWorkflowModelId = deployedWorkflowModelId;
        this.serverId = serverId;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof WorkflowModelIsDeployedOnServerId)) {
            return false;
        }
        WorkflowModelIsDeployedOnServerId castOther = (WorkflowModelIsDeployedOnServerId) other;

        return (this.getDeployedWorkflowModelId() == castOther
                .getDeployedWorkflowModelId())
                && (this.getServerId() == castOther.getServerId());
    }

    /**
     * Gets the deployed workflow model id.
     * 
     * @return the deployed workflow model id
     */
    public long getDeployedWorkflowModelId() {
        return this.deployedWorkflowModelId;
    }

    /**
     * Gets the server id.
     * 
     * @return the server id
     */
    public long getServerId() {
        return this.serverId;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getDeployedWorkflowModelId();
        result = 37 * result + (int) this.getServerId();
        return result;
    }

    /**
     * Sets the deployed workflow model id.
     * 
     * @param deployedWorkflowModelId
     *            the new deployed workflow model id
     */
    public void setDeployedWorkflowModelId(long deployedWorkflowModelId) {
        this.deployedWorkflowModelId = deployedWorkflowModelId;
    }

    /**
     * Sets the server id.
     * 
     * @param serverId
     *            the new server id
     */
    public void setServerId(long serverId) {
        this.serverId = serverId;
    }

}
