/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkItem generated by hbm2java.
 */
public class WorkItem implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private Long id;
    
    /** The workflow instance. */
    private WorkflowInstance workflowInstance;
    
    /** The user. */
    private User user;
    
    /** The creation date. */
    private Date creationDate;
    
    /** The status. */
    private String status;
    
    /** The data. */
    private byte[] data;
    
    /** The name. */
    private String name;
    
    /** The description. */
    private String description;
    
    /** The work item contains files. */
    private Set<WorkItemContainsFile> workItemContainsFiles = new HashSet<WorkItemContainsFile>(
            0);

    /**
     * Instantiates a new work item.
     */
    public WorkItem() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new work item.
     * 
     * @param workflowInstance
     *            the workflow instance
     * @param user
     *            the user
     * @param creationDate
     *            the creation date
     * @param status
     *            the status
     * @param data
     *            the data
     * @param name
     *            the name
     * @param description
     *            the description
     */
    public WorkItem(WorkflowInstance workflowInstance, User user,
            Date creationDate, String status, byte[] data, String name,
            String description) {
        // generated minimal constructor
        this.workflowInstance = workflowInstance;
        this.user = user;
        this.creationDate = creationDate;
        this.status = status;
        this.data = data;
        this.name = name;
        this.description = description;
    }

    /**
     * Instantiates a new work item.
     * 
     * @param workflowInstance
     *            the workflow instance
     * @param user
     *            the user
     * @param creationDate
     *            the creation date
     * @param status
     *            the status
     * @param data
     *            the data
     * @param name
     *            the name
     * @param description
     *            the description
     * @param workItemContainsFiles
     *            the work item contains files
     */
    public WorkItem(WorkflowInstance workflowInstance, User user,
            Date creationDate, String status, byte[] data, String name,
            String description, Set<WorkItemContainsFile> workItemContainsFiles) {
        // generated full constructor
        this.workflowInstance = workflowInstance;
        this.user = user;
        this.creationDate = creationDate;
        this.status = status;
        this.data = data;
        this.name = name;
        this.description = description;
        this.workItemContainsFiles = workItemContainsFiles;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the workflow instance.
     * 
     * @return the workflow instance
     */
    public WorkflowInstance getWorkflowInstance() {
        return this.workflowInstance;
    }

    /**
     * Sets the workflow instance.
     * 
     * @param workflowInstance
     *            the new workflow instance
     */
    public void setWorkflowInstance(WorkflowInstance workflowInstance) {
        this.workflowInstance = workflowInstance;
    }

    /**
     * Gets the user.
     * 
     * @return the user
     */
    public User getUser() {
        return this.user;
    }

    /**
     * Sets the user.
     * 
     * @param user
     *            the new user
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Gets the creation date.
     * 
     * @return the creation date
     */
    public Date getCreationDate() {
        return this.creationDate;
    }

    /**
     * Sets the creation date.
     * 
     * @param creationDate
     *            the new creation date
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * Gets the status.
     * 
     * @return the status
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Sets the status.
     * 
     * @param status
     *            the new status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Gets the data.
     * 
     * @return the data
     */
    public byte[] getData() {
        return this.data;
    }

    /**
     * Sets the data.
     * 
     * @param data
     *            the new data
     */
    public void setData(byte[] data) {
        this.data = data;
    }

    /**
     * Gets the name.
     * 
     * @return the name
     */
    public String getName() {
        return this.name;
    }

    /**
     * Sets the name.
     * 
     * @param name
     *            the new name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the description.
     * 
     * @return the description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Sets the description.
     * 
     * @param description
     *            the new description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the work item contains files.
     * 
     * @return the work item contains files
     */
    public Set<WorkItemContainsFile> getWorkItemContainsFiles() {
        return this.workItemContainsFiles;
    }

    /**
     * Sets the work item contains files.
     * 
     * @param workItemContainsFiles
     *            the new work item contains files
     */
    public void setWorkItemContainsFiles(
            Set<WorkItemContainsFile> workItemContainsFiles) {
        this.workItemContainsFiles = workItemContainsFiles;
    }

}
