/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 28.12.2009 10:39:25 by Hibernate Tools 3.2.4.GA

/**
 * WorkflowModelIsDeployedOnServer generated by hbm2java.
 */
public class WorkflowModelIsDeployedOnServer implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private WorkflowModelIsDeployedOnServerId id;

    /** The deployed workflow model. */
    private DeployedWorkflowModel deployedWorkflowModel;

    /** The server. */
    private Server server;

    /**
     * Instantiates a new workflow model is deployed on server.
     */
    public WorkflowModelIsDeployedOnServer() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new workflow model is deployed on server.
     * 
     * @param id
     *            the id
     * @param deployedWorkflowModel
     *            the deployed workflow model
     * @param server
     *            the server
     */
    public WorkflowModelIsDeployedOnServer(
            WorkflowModelIsDeployedOnServerId id,
            DeployedWorkflowModel deployedWorkflowModel, Server server) {
        // generated full constructor
        this.id = id;
        this.deployedWorkflowModel = deployedWorkflowModel;
        this.server = server;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public WorkflowModelIsDeployedOnServerId getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(WorkflowModelIsDeployedOnServerId id) {
        this.id = id;
    }

    /**
     * Gets the deployed workflow model.
     * 
     * @return the deployed workflow model
     */
    public DeployedWorkflowModel getDeployedWorkflowModel() {
        return this.deployedWorkflowModel;
    }

    /**
     * Sets the deployed workflow model.
     * 
     * @param deployedWorkflowModel
     *            the new deployed workflow model
     */
    public void setDeployedWorkflowModel(
            DeployedWorkflowModel deployedWorkflowModel) {
        this.deployedWorkflowModel = deployedWorkflowModel;
    }

    /**
     * Gets the server.
     * 
     * @return the server
     */
    public Server getServer() {
        return this.server;
    }

    /**
     * Sets the server.
     * 
     * @param server
     *            the new server
     */
    public void setServer(Server server) {
        this.server = server;
    }

}
