package de.decidr.model.entities;

// Generated 14.12.2009 17:42:31 by Hibernate Tools 3.2.4.GA

/**
 * WorkItemContainsFileId generated by hbm2java
 */
public class WorkItemContainsFileId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private long workItemId;
    private long fileId;

    public WorkItemContainsFileId() {
        //default empty JavaBean constructor
    }

    public WorkItemContainsFileId(long workItemId, long fileId) {
        //generated full constructor
        this.workItemId = workItemId;
        this.fileId = fileId;
    }

    public long getWorkItemId() {
        return this.workItemId;
    }

    public void setWorkItemId(long workItemId) {
        this.workItemId = workItemId;
    }

    public long getFileId() {
        return this.fileId;
    }

    public void setFileId(long fileId) {
        this.fileId = fileId;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof WorkItemContainsFileId))
            return false;
        WorkItemContainsFileId castOther = (WorkItemContainsFileId) other;

        return (this.getWorkItemId() == castOther.getWorkItemId())
                && (this.getFileId() == castOther.getFileId());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getWorkItemId();
        result = 37 * result + (int) this.getFileId();
        return result;
    }

}
