package de.decidr.model.entities;

// Generated 29.05.2009 18:32:43 by Hibernate Tools 3.2.2.GA

/**
 * WorkItemSummaryView generated by hbm2java
 */
public class WorkItemSummaryView implements java.io.Serializable {

    private WorkItemSummaryViewId id;

    public WorkItemSummaryView() {
    }

    public WorkItemSummaryView(WorkItemSummaryViewId id) {
        this.id = id;
    }

    public WorkItemSummaryViewId getId() {
        return this.id;
    }

    public void setId(WorkItemSummaryViewId id) {
        this.id = id;
    }

}
