/*
 * The DecidR Development Team licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package de.decidr.model.entities;

// Generated 22.01.2010 14:51:15 by Hibernate Tools 3.2.4.GA

/**
 * WorkItemContainsFile generated by hbm2java.
 */
public class WorkItemContainsFile implements java.io.Serializable {

    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The id. */
    private WorkItemContainsFileId id;
    
    /** The work item. */
    private WorkItem workItem;
    
    /** The file. */
    private File file;

    /**
     * Instantiates a new work item contains file.
     */
    public WorkItemContainsFile() {
        // default empty JavaBean constructor
    }

    /**
     * Instantiates a new work item contains file.
     * 
     * @param id
     *            the id
     * @param workItem
     *            the work item
     * @param file
     *            the file
     */
    public WorkItemContainsFile(WorkItemContainsFileId id, WorkItem workItem,
            File file) {
        // generated full constructor
        this.id = id;
        this.workItem = workItem;
        this.file = file;
    }

    /**
     * Gets the id.
     * 
     * @return the id
     */
    public WorkItemContainsFileId getId() {
        return this.id;
    }

    /**
     * Sets the id.
     * 
     * @param id
     *            the new id
     */
    public void setId(WorkItemContainsFileId id) {
        this.id = id;
    }

    /**
     * Gets the work item.
     * 
     * @return the work item
     */
    public WorkItem getWorkItem() {
        return this.workItem;
    }

    /**
     * Sets the work item.
     * 
     * @param workItem
     *            the new work item
     */
    public void setWorkItem(WorkItem workItem) {
        this.workItem = workItem;
    }

    /**
     * Gets the file.
     * 
     * @return the file
     */
    public File getFile() {
        return this.file;
    }

    /**
     * Sets the file.
     * 
     * @param file
     *            the new file
     */
    public void setFile(File file) {
        this.file = file;
    }

}
