package de.decidr.model.entities;

// Generated 12.06.2009 08:13:27 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * WorkItemSummaryView generated by hbm2java
 */
public class WorkItemSummaryView implements java.io.Serializable {

    private long id;
    private String workItemName;
    private String tenantName;
    private Date creationDate;
    private String workItemStatus;

    public WorkItemSummaryView() {
    }

    public WorkItemSummaryView(long id, String workItemName, String tenantName,
            Date creationDate, String workItemStatus) {
        this.id = id;
        this.workItemName = workItemName;
        this.tenantName = tenantName;
        this.creationDate = creationDate;
        this.workItemStatus = workItemStatus;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getWorkItemName() {
        return this.workItemName;
    }

    public void setWorkItemName(String workItemName) {
        this.workItemName = workItemName;
    }

    public String getTenantName() {
        return this.tenantName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getWorkItemStatus() {
        return this.workItemStatus;
    }

    public void setWorkItemStatus(String workItemStatus) {
        this.workItemStatus = workItemStatus;
    }

    // The following is extra code specified in the hbm.xml files
    private static final long serialVersionUID = 1L;
    // end of extra code specified in the hbm.xml files

}
